/* Generic supplementary technique teaching. Never a clinical finding or exam credit. */
(()=>{
const lessons={
 lungs:{title:'Compare the lungs',region:'Lungs',source:'https://stanfordmedicine25.stanford.edu/the25/pulmonary.html',steps:[
  {title:'Same level, other side',text:'This is a posterior view. After listening at an upper right field, compare the matching left field before moving lower.',question:'Where should your next comparison be?',choices:['The matching upper left field','The right base'],answer:0,why:'Paired positions help you notice asymmetry instead of relying on memory across the whole chest.'},
  {title:'Make the comparison fair',text:'The path pairs right and left fields. Explain the examination, maintain appropriate exposure and draping, and listen on skin while the patient breathes through an open mouth.',question:'What should stay comparable?',choices:['Only the side that sounds louder','The level and listening conditions'],answer:1,why:'Use a systematic comparison. A drawing cannot establish what this patient’s lungs sound like.'},
  {title:'Continue down in pairs',text:'Now move to the next level and compare across. Your course describes six posterior fields, with side-to-side comparison, mouth open and on skin.',question:'After the next right-sided position…',choices:['Compare the left at the same level','Document both bases as clear'],answer:0,why:'You still need to actually obtain each finding. A normal upper field does not establish normal lower fields.'},
  {title:'Transfer the pattern',text:'The same paired-comparison habit applies when percussing appropriate lung fields. Listen, compare, move; do not let the diagram replace your examination choices.',question:'What can you document from this demonstration alone?',choices:['No patient-specific examination finding','Normal breath sounds bilaterally'],answer:0,why:'This was technique rehearsal. Perform an examination in the actual encounter to obtain evidence.'}
 ]},
 abdomen:{title:'Sequence the abdominal exam',region:'Abdomen',source:'https://www.merckmanuals.com/professional/gastrointestinal-disorders/acute-abdomen-and-surgical-gastroenterology/acute-abdominal-pain',steps:[
  {title:'Look before you touch',text:'The same patient is shown supine for this visual rehearsal; the recorded encounter position is unchanged. Explain the examination, check comfort, and expose only what is needed. Begin by inspecting the abdomen.',question:'After inspection, what comes next in the usual sequence?',choices:['Deep palpation immediately','Auscultation'],answer:1,why:'Use a repeatable sequence: inspect, auscultate, percuss, palpate.'},
  {title:'Listen before percussion and palpation',text:'The stethoscope represents auscultation. You must select the areas and technique you intend to perform in the real encounter.',question:'What follows auscultation?',choices:['Percussion, then palpation','Assume all quadrants are normal'],answer:0,why:'A sequence supports recall, but each finding still needs an actual examination action.'},
  {title:'Percuss, then begin gently',text:'The placement ring illustrates where an action could occur; it does not animate a hand or verify finger technique or force. Before palpation, ask where the pain is greatest.',question:'Where should gentle palpation begin?',choices:['Away from the area of greatest pain','At the most painful point with deep pressure'],answer:0,why:'Start gently away from maximal pain, watch the patient, and adapt to comfort and clinical context.'},
  {title:'Apply it to this encounter',text:'Do not treat the sequence as a demand to complete every maneuver in every patient. Appropriate urgency, comfort and the clinical question guide your choices.',question:'An omitted maneuver allows you to write…',choices:['A normal finding if it is likely','That it was not assessed, when relevant'],answer:1,why:'Hidden case truth is not documentation evidence. Only obtained or authorized supplied findings belong in Objective.'}
 ]},
 positional:{title:'Prepare a positional test',region:'Neurologic',source:'https://www.entnet.org/resource/aao-hnsf-updated-cpg-bppv-press-release-fact-sheet/',steps:[
  {title:'Check suitability first',text:'Before a Dix–Hallpike maneuver, assess whether the history fits positional vertigo, explain the test, and assess safe neck movement and relevant cervical or vascular risks. This visual guide is not permission to move this patient in the actual encounter.',question:'What comes before head or body movement?',choices:['Immediately lower the patient','Establish suitability and obtain permission'],answer:1,why:'If neck movement is unsafe or suitability is uncertain, do not force the maneuver; choose an appropriate alternative or seek supervision.'},
  {title:'Turn, support, then reposition',text:'The angle guide shows about 45° of head rotation for the illustrated side. The patient’s head does not perform this rotation. The examiner must support the patient and head throughout the actual maneuver; this overlay is a preparation aid, not a hands-on demonstration.',question:'What must be maintained while repositioning?',choices:['Support and the intended head orientation','Unrestricted neck extension'],answer:0,why:'The usual maneuver uses the selected head rotation and about 20° neck extension when safely positioned supine. No unsupported rapid movement is demonstrated here.'},
  {title:'Observe rather than assume',text:'The line indicates where head support is needed; the supine model does not reproduce the required neck extension. Observe symptoms and the eyes after appropriate positioning. No nystagmus is shown: the case result must come from the actual examination system.',question:'Does reaching this position prove a positive result?',choices:['Yes, the position establishes the diagnosis','No, symptoms and eye findings must be assessed'],answer:1,why:'The diagnostic result depends on observed findings. A generic animation cannot supply them.'},
  {title:'Keep side-specific evidence',text:'The alternate angle guide points toward the other side; the model’s head remains neutral. Return the patient safely upright and consider the other side when appropriate; do not credit an untested side.',question:'After testing one side only, what is supported?',choices:['Only that side’s obtained findings','Normal results on both sides'],answer:0,why:'Now select the actual maneuver and explicit components in the encounter. Cervical suitability is a prerequisite, not automatic credit from watching this lesson.'}
 ]}
};
let lessonId=null,step=0,answered=false,priorFocus=null;
const launch=document.createElement('button');launch.id='techniqueLaunch';launch.textContent='Learn an examination sequence';launch.hidden=true;document.querySelector('#room').append(launch);
const panel=document.createElement('section');panel.id='techniquePanel';panel.hidden=true;panel.setAttribute('aria-label','Interactive technique teaching');document.querySelector('#room').append(panel);
window.pcmTechniqueNotice=message=>{const feedback=panel.querySelector('.tech-feedback');if(feedback)feedback.textContent=message;else status(message);};
function report(event,extra={}){send({type:'pcm-unity-teaching',sessionId:state.sessionId,lessonId,step,event,...extra})}
function stop(){if(instance)instance.SendMessage('EncounterBridge','StopTechnique','');panel.hidden=true;lessonId=null;apply();priorFocus?.focus()}
function menu(){if(!['guided','coached'].includes(state.mode))return;priorFocus=document.activeElement;panel.hidden=false;panel.innerHTML='<button class="tech-close" aria-label="Close technique studio">×</button><small>SUPPLEMENTARY TEACHING</small><h2>Rehearse a sequence</h2><p>Practice with an overlay on your current patient. Temporary viewing positions do not change the recorded encounter position or create findings.</p>'+Object.entries(lessons).map(([id,l])=>'<button class="lesson-choice" data-lesson="'+id+'">'+l.title+'</button>').join('');panel.querySelector('.tech-close').onclick=stop;panel.querySelectorAll('[data-lesson]').forEach(b=>b.onclick=()=>{lessonId=b.dataset.lesson;step=0;report('start');render()})}
function render(){const lesson=lessons[lessonId],item=lesson.steps[step];answered=false;panel.hidden=false;$('drawer').hidden=true;panel.innerHTML='<button class="tech-close" aria-label="Close technique studio">×</button><small>TECHNIQUE OVERLAY · '+(step+1)+' / '+lesson.steps.length+'</small><h2>'+item.title+'</h2><p>'+item.text+'</p><strong>'+item.question+'</strong><div class="tech-choices">'+item.choices.map((c,i)=>'<button data-answer="'+i+'">'+c+'</button>').join('')+'</div><div class="tech-feedback" role="status"></div><button id="techNext" hidden>Next comparison</button><p class="tech-limit">No patient findings or examination credit are created. <a target="_blank" rel="noopener" href="'+lesson.source+'">Clinical reference</a></p>';
 panel.querySelector('.tech-close').onclick=stop;panel.querySelectorAll('[data-answer]').forEach(b=>b.onclick=()=>{const correct=Number(b.dataset.answer)===item.answer;report('answer',{choice:b.textContent,correct});panel.querySelector('.tech-feedback').textContent=(correct?'Yes. ':'Try again. ')+item.why;if(correct){answered=true;panel.querySelectorAll('[data-answer]').forEach(x=>x.disabled=true);const next=$('techNext');next.hidden=false;next.textContent=step===lesson.steps.length-1?'Return and choose an actual exam':'Next comparison';}});
 $('techNext').onclick=()=>{if(!answered)return;if(step===lesson.steps.length-1){const region=lesson.region;report('complete');stop();openRegion(region);status('Choose the actual examination and components now. The lesson itself obtained no findings.');}else{step++;render()}};
 if(instance)instance.SendMessage('EncounterBridge','ShowTechnique',JSON.stringify({lesson:lessonId,step}));panel.querySelector('h2').tabIndex=-1;panel.querySelector('h2').focus();window.pcmTechniqueState?.();
}
launch.onclick=menu;window.pcmTechniqueState=()=>{const allowed=['guided','coached'].includes(state.mode)&&state.phase==='encounter';launch.hidden=!allowed;launch.disabled=!!pending||state.busyMs>0;if(!allowed||state.busyMs>0){if(!panel.hidden)stop()}if(lessonId){$('name').textContent='Patient · technique overlay';$('phase').textContent='Technique rehearsal · no patient findings';}if(lessonId)document.querySelectorAll('[data-region],#perform,#comfort,#hygiene,#position,[data-posture],[data-view],#resetView,#adjustView,[data-camera]').forEach(b=>b.disabled=true)};
})();
