"""Individually authored September 2026 CSE expansion; fictional patient details.

This is a deterministic serializer, not a diagnosis or treatment generator.
Clinical references support presentation/management direction, not fictional facts.
"""
from pathlib import Path
import copy,json,sys
ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT))
from pcmcse import physexam
DATE='2026-09-14'
CASES=[]

def add(cid,name,age,sex,system,title,opening,hpi,hist,ros,exams,dx,plans,source,goal,decision,closing,concern,vitals=None,extra=None):
    CASES.append(dict(cid=cid,name=name,age=age,sex=sex,system=system,title=title,opening=opening,hpi=hpi,hist=hist,ros=ros,exams=exams,dx=dx,plans=plans,source=source,goal=goal,decision=decision,closing=closing,concern=concern,vitals=vitals,extra=extra or []))
# HPI rows: id/category, topic, unique spoken question, exact answer, clinical note wording.
def H(key,label,q,a,n): return (key,label,q,a,n)
def R(key,system,pos,a,n=None): return (key,system,pos,a,n or a)
def E(mid,text,components=None,core=True):return (mid,text,components,core)
def D(name,cat,ids,reason,aliases=None):return (name,cat,ids,reason,aliases or [name])
def X(kind,label,q,a,n=None):return (kind,label,q,a,n or a)

add('cardio-exertional-leg-pain','Daniel Brooks',59,'male','Cardiovascular','Calf pain with walking','My left calf cramps whenever I walk a couple of blocks.',[
H('onset','Onset','When did the calf pain start?','It started about 3 months ago.','Three months of exertional left calf pain.'),
H('location','Location','Where is the pain?','It is in the back of my left calf.','Pain is localized to the left calf.'),
H('radiation','Spread','Does the calf pain spread?','It stays in the calf.','No radiation.'),
H('quality','Character','What does the calf pain feel like?','A tight cramp, as if the muscle is squeezing.','Cramping tightness.'),
H('severity','Severity and function','How severe is the calf pain?','About 6 out of 10. I have to stop walking.','6/10 and limits walking.'),
H('timing','Episode duration','How long does each cramp last?','It settles within about 3 minutes after I stop.','Resolves within 3 minutes of rest.'),
H('chronology','Change over time','How has your walking distance changed?','At first I could walk six blocks. Now it starts after about two.','Walking threshold decreased from six to two blocks.'),
H('setting','Activity','What activity brings on the calf pain?','Walking fast or uphill brings it on sooner.','Provoked earlier by brisk walking or hills.'),
H('alleviating','Relief','Do you have to sit or bend forward to relieve it?','No. Just standing still is enough.','Standing rest suffices without lumbar flexion.'),
H('aggravating','Trigger','Does standing still bring on pain?','No, standing still does not cause it.','Not provoked by standing alone.'),
H('treatment','Self-treatment','What have you tried for the calf pain?','I tried stretching, but it did not help.','Stretching ineffective.'),
H('past_occurrence','Earlier episodes','Have you had this before these three months?','No, this is new for me.','No earlier episodes.')],
[
X('pmh','Hypertension and lipids','What medical conditions do you have?','I have high blood pressure and high cholesterol.','Hypertension and hyperlipidemia.'),
X('pmh','Diabetes','Have you been diagnosed with diabetes?','No, I have not been diagnosed with diabetes.','No known diabetes.'),
X('psh','Surgery','What operations have you had?','My appendix was removed when I was 19.','Appendectomy at 19.'),
X('medications','Daily medication','What medicines do you take?','Lisinopril 20 milligrams every morning. I stopped atorvastatin 20 milligrams 6 months ago because the refill was expensive.','Lisinopril 20 mg daily; stopped atorvastatin 20 mg 6 months ago because of cost.'),
X('allergies','Drug reactions','Do you have medication allergies?','Penicillin gave me hives when I was a teenager. I did not have breathing trouble.','Penicillin: hives, no respiratory reaction.'),
X('social','Smoking','Do you smoke?','I smoke a pack a day and have for 35 years.','Current tobacco: 35 pack-years.'),
X('social','Alcohol','How much alcohol do you drink?','One beer on most Saturday evenings.','Approximately one beer weekly.'),
X('social','Drugs','Do you use recreational drugs?','No.','No recreational drugs.'),
X('social','Work','What do you do for work?','I supervise a warehouse. Walking the floor has become difficult.','Warehouse supervisor; walking duties limited.'),
X('social','Home and support','Who lives with you?','My husband lives with me and can drive me to appointments.','Lives with husband; transport available.'),
X('family','Father','What health problems did your father have?','My father had a heart attack at 54.','Father: myocardial infarction at 54.'),
X('family','Mother','What health problems does your mother have?','My mother has type 2 diabetes.','Mother: type 2 diabetes.')],
[R('chest_pain','cardiovascular',False,'I have not had chest pain.','No chest pain.'),R('dyspnea','cardiovascular',False,'I am not short of breath.','No dyspnea.'),R('edema','cardiovascular',False,'Neither leg has been swollen.','No edema.'),R('back_pain','musculoskeletal',True,'My lower back sometimes aches after a long shift, but it does not spread down my leg.','Occasional nonradiating low-back ache after work.'),R('joint_pain','musculoskeletal',False,'My hip and knee do not hurt.','No hip or knee pain.'),R('myalgia','musculoskeletal',True,'Only that left calf cramps with walking.','Exertional left calf cramping.'),R('numbness','neurologic',False,'My feet do not feel numb.','No numbness.'),R('tingling','neurologic',False,'I have not had pins and needles.','No paresthesias.'),R('weakness','neurologic',False,'My leg is not weak; I stop because of the cramp.','No focal weakness.')],
[E('general_inspect','Alert, comfortable at rest, without respiratory distress.'),E('heart_auscultate','Regular rate and rhythm without murmur.'),E('lungs_auscultate','Breath sounds clear bilaterally.',['posterior','on skin','compare side to side','mouth open']),E('peripheral_pulses','Left dorsalis pedis and posterior tibial pulses 1+; right pedal pulses 2+.',['dorsalis pedis','posterior tibial']),E('extremities','Left foot slightly cooler than right; capillary refill 3 seconds left and 2 seconds right. No edema or calf asymmetry.',['capillary refill','edema','calf symmetry']),E('skin_inspect','Reduced hair over the left lower leg; no ulcer or tissue loss on inspected legs and feet.',['legs','soles']),E('msk_palpate','No focal calf or knee tenderness. Mild bilateral lumbar paraspinal tenderness.',['point tenderness','paraspinal musculature']),E('neuro_sensory','Light touch intact in both feet.',['light touch']),E('msk_strength','Ankle dorsiflexion and plantarflexion 5/5 bilaterally.',['lower extremity']),E('osteo_screen','L3 bilateral lumbar paraspinal tissue texture change and tenderness.',['lumbar'],False)],
[D('Peripheral artery disease with intermittent claudication','V',['hpi_timing','hpi_chronology','history_smoking','exam_peripheral_pulses'],'Reproducible exertional calf pain, rapid standing-rest relief and asymmetric pedal pulses support arterial disease.'),D('Lumbar spinal stenosis with neurogenic claudication','D',['symptom_back_pain','hpi_setting'],'Exertional leg symptoms and back discomfort warrant consideration; lack of posture dependence and pulse asymmetry argue against it as the main cause.'),D('Calf muscle overuse or strain','T',['hpi_quality','history_work'],'Walking-related muscular pain is possible, but progression and vascular findings favor arterial disease.')],
['Obtain resting ankle-brachial indices and assess cardiovascular risk; use exercise ABI if resting results are nondiagnostic. If PAD is confirmed, discuss single antiplatelet and high-intensity statin therapy after contraindication review, structured walking, smoking cessation and daily foot care. Address refill cost; review in 2 weeks. Sudden persistent pain, pallor, coldness or weakness needs emergency care.','If vascular testing does not explain symptoms, reassess posture dependence and neurologic findings; pursue lumbar evaluation as indicated. Encourage tolerable activity and explain emergency bladder, saddle-sensation or weakness symptoms; arrange follow-up within 2 weeks.','If a muscular cause remains likely after vascular assessment, use relative rest, gentle rehabilitation and safe analgesia rather than forcing painful exercise. Explain a gradual return to work and activity after vascular causes have been assessed.'],
[('2024 PAD guideline implementation','https://www.acc.org/Latest-in-Cardiology/Articles/2024/09/01/01/42/Peripheral-Matters-PAD-Putting-the-2024-Guideline-Into-Practice')],
'Distinguish vascular walking pain from posture-dependent or muscular pain.','Does standing still relieve it, or must you sit and bend forward?','I will check the circulation in your legs and arrange a pressure comparison at your ankles. We will also work on affordable medicines and stopping smoking. Sudden pain that does not stop, or a cold or weak foot, needs emergency help.','I can look for an affordable refill and arrange a follow-up in two weeks. Your husband can join the discussion if you want.',vitals={'BP':'148/86 mmHg','P':'78 bpm','R':'16 rpm','T':'98.4 F oral','Pulse Ox':'98% on room air','Ht':'5\' 10"','Wt':'194 lbs'},extra=[X('pertinent_negative','Rest pain and wounds','Do you have foot pain at rest or sores that will not heal?','No pain at rest and no sores.','No rest pain or nonhealing wounds.')])

add('pulm-episodic-wheeze','Sofia Patel',27,'female','Respiratory','Episodes of wheezing and chest tightness','I keep getting spells of wheezing and a tight chest.',[
H('onset','Onset','When did the wheezing begin?','About 6 weeks ago.','Six weeks of intermittent wheezing and chest tightness.'),H('location','Location','Where do you feel the tightness?','Across my chest, not in one spot.','Diffuse chest tightness.'),H('quality','Character','What is breathing like during a spell?','It whistles when I breathe out, and getting air out feels hard.','Expiratory wheeze and difficulty exhaling.'),H('severity','Function','How much do the spells limit you?','I stop jogging and wait. I can still speak in full sentences.','Interrupts jogging; speech maintained.'),H('timing','Duration and frequency','How long do the spells last and how often do they happen?','Usually 10 to 20 minutes, about 3 days a week.','Episodes 10–20 minutes, approximately 3 days weekly.'),H('chronology','Nighttime symptoms','Do symptoms wake you at night?','A dry cough wakes me about once a week.','Weekly nocturnal cough.'),H('setting','Work exposure','Is there a pattern at work or away from work?','Flour dust in the bakery sets it off. I was better during four days away.','Flour-dust exposure at bakery; improved during 4 days away.'),H('aggravating','Other triggers','What else brings it on?','Cold-air jogging and strong cleaning sprays.','Cold air and cleaning sprays also trigger symptoms.'),H('alleviating','Relief','What helps the wheezing?','Stopping and getting away from the dust helps.','Improves with rest and exposure avoidance.'),H('treatment','Inhaler use','Have you tried an inhaler?','No, I have never had an inhaler.','No prior inhaler trial.'),H('past_occurrence','Past breathing trouble','Did you have this as a child?','I had hay fever, but no diagnosed asthma.','Childhood allergic rhinitis without prior asthma diagnosis.')],
[X('pmh','Medical history','What medical conditions do you have?','Seasonal hay fever and occasional heartburn.','Seasonal allergic rhinitis; occasional heartburn.'),X('psh','Procedures','Have you had surgery?','Only wisdom teeth removal at 20.','Wisdom teeth removed at 20.'),X('medications','Medication','What medicines do you take?','Cetirizine 10 milligrams when pollen is bad, and a chewable antacid about once a week.','Cetirizine 10 mg as needed; antacid approximately weekly.'),X('allergies','Drug reactions','Are you allergic to medicines?','Trimethoprim-sulfamethoxazole gave me a widespread rash when I was 17, without blisters or breathing trouble.','TMP-SMX: nonblistering rash at 17, no respiratory symptoms.'),X('social','Smoking','Do you smoke or vape?','I have never smoked or vaped.','Never smoked or vaped.'),X('social','Alcohol','How much alcohol do you drink?','I do not drink alcohol.','No alcohol.'),X('social','Drugs','Do you use recreational drugs?','No.','No recreational drugs.'),X('social','Work','What does your job involve?','I mix dough at a bakery. There is visible flour dust, and masks are not consistently available.','Bakery dough mixing with flour exposure; inconsistent respiratory protection.'),X('social','Home','Who do you live with?','Two roommates. There are no pets or smokers at home.','Lives with two roommates; no household pets or smoke.'),X('family','Family history','Does asthma or allergy run in your family?','My mother has asthma and my brother has eczema.','Mother: asthma; brother: eczema.'),X('obgyn','Pregnancy possibility','Could you be pregnant?','My period was two weeks ago. I use an IUD and do not think I am pregnant.','LMP 2 weeks ago; IUD; pregnancy not suspected by patient.')],
[R('cough','respiratory',True,'I get a dry cough, especially at night.','Dry nocturnal cough.'),R('dyspnea','respiratory',True,'I am short of breath during the spells, not when resting now.','Episodic dyspnea; none at rest now.'),R('hemoptysis','respiratory',False,'I have not coughed up blood.','No hemoptysis.'),R('rhinorrhea','heent',True,'My nose runs when pollen is high.','Seasonal rhinorrhea.'),R('sore_throat','heent',True,'Sometimes my throat feels tight during a spell.','Occasional throat tightness with episodes.'),R('hoarseness','heent',True,'My voice sometimes goes raspy after a spell.','Transient postepisode hoarseness.'),R('fever','general',False,'I have not had a fever.','No fever.'),R('fatigue','general',True,'I am tired after a night of coughing.','Fatigue after disrupted sleep.'),R('weight_loss','general',False,'My weight has stayed the same.','No weight loss.')],
[E('general_inspect','Alert, speaking comfortably in full sentences; no respiratory distress.'),E('chest_inspect','Symmetric chest movement without accessory muscle use.',['symmetry','accessory muscle use']),E('lungs_auscultate','Mild bilateral expiratory wheezes with prolonged expiration; no focal crackles.',['posterior','on skin','compare side to side','mouth open']),E('heart_auscultate','Regular rate and rhythm without murmur.'),E('heent_nose','Pale edematous nasal mucosa with clear secretions bilaterally.',['right naris','left naris']),E('heent_throat','No tonsillar swelling or exudate; voice clear at rest.',['oropharynx','tonsils']),E('osteo_screen','T3 right paraspinal tissue texture change and tenderness.',['thoracic'],False)],
[D('Asthma, possibly work-related','A',['hpi_setting','hpi_timing','exam_lungs_auscultate'],'Variable nocturnal/exertional symptoms, atopy and expiratory wheeze support asthma; work association requires evaluation.'),D('Inducible laryngeal obstruction','F',['symptom_sore_throat','symptom_hoarseness','hpi_aggravating'],'Episodic throat tightness and voice change with irritants support consideration; expiratory wheeze favors asthma and both may coexist.'),D('Gastroesophageal reflux with airway symptoms','I',['history_medical_history','history_medication','hpi_chronology'],'Reported heartburn and nocturnal cough support reflux as a contributor, but do not explain all wheezing.')],
['Arrange pre/post-bronchodilator spirometry; consider serial peak-flow records at and away from work and occupational review. Start an inhaled-corticosteroid-containing plan if asthma is established; teach inhaler technique and an action plan. Reduce dust exposure without assuming she must quit work; review in 2 weeks. Severe breathlessness or inability to speak needs emergency help.','If throat/voice episodes persist or lung tests do not explain them, refer for laryngeal assessment during symptoms and breathing retraining. Discuss irritant avoidance and explain overlap with asthma; review the referral at the 2-week visit.','If reflux symptoms persist, use meal-timing/trigger measures and consider a supervised acid-suppression trial after review. Explain that reflux treatment does not replace respiratory evaluation; reassess symptom response in 4 weeks.'],
[('Asthma diagnosis','https://www.nhlbi.nih.gov/health/asthma/diagnosis'),('Asthma treatment and occupational asthma','https://www.nhlbi.nih.gov/health/asthma/treatment-action-plan')],
'Characterize variable obstruction and distinguish lung wheeze from throat symptoms.','Do spells occur at work, away from work, or during sleep?','I will arrange breathing tests and review the work pattern. If we confirm asthma, we will choose an inhaler plan and practice using it. Severe trouble breathing or speaking means seek emergency help.','We can discuss safer flour handling and protection with occupational health, with your permission, rather than assuming you must leave your job.',extra=[X('concern','Patient concern','What worries you most?','I am worried I will have to quit the bakery.','Concerned about job loss.')])

add('pulm-chronic-productive-cough','Marcus Hill',56,'male','Respiratory','Persistent morning cough and exertional breathlessness','I cough up mucus every morning and get winded more easily.',[
H('onset','Onset','How long have you had the cough?','For about two years.','Productive cough for 2 years.'),H('quality','Sputum','What do you cough up?','A few tablespoons of white mucus most mornings.','Several tablespoons of white morning sputum.'),H('timing','Pattern','Is the cough present every day?','Most days, including through both winters and summers.','Symptoms most days year-round.'),H('chronology','Progression','How has your breathing changed?','Over 6 months I have gone from climbing two flights easily to stopping after one.','Progressive exertional dyspnea over 6 months; now stops after one flight.'),H('severity','Current function','Are you breathless while resting or talking?','No, I am comfortable sitting and talking.','No resting or conversational dyspnea.'),H('location','Chest symptoms','Where do you feel the breathing discomfort?','Across my chest when I am exerting myself.','Diffuse exertional breathing discomfort.'),H('setting','Exposure','What exposures have you had at work?','I worked around diesel exhaust at a loading dock for 25 years.','25 years of loading-dock diesel exposure.'),H('aggravating','Triggers','What makes the cough or breathing worse?','Stairs, smoke and cold mornings.','Worse with exertion, smoke and cold air.'),H('alleviating','Relief','What helps?','Rest helps my breathing, and coughing clears the mucus for a while.','Rest relieves dyspnea; expectoration temporarily clears mucus.'),H('treatment','Self-treatment','What have you tried for the cough?','A cough syrup did not help. I have never used an inhaler.','Cough syrup ineffective; no inhaler use.'),H('past_occurrence','Respiratory infections','Have you had chest infections before?','I was treated for two chest infections in the past three years.','Two treated chest infections in 3 years.')],
[X('pmh','Medical conditions','What medical conditions have you been diagnosed with?','High blood pressure. Nobody has diagnosed a lung condition.','Hypertension; no established lung diagnosis.'),X('psh','Surgery','Have you had surgery?','My gallbladder was removed at 42.','Cholecystectomy at 42.'),X('medications','Medication','What medicines do you take?','Amlodipine 5 milligrams each morning.','Amlodipine 5 mg daily.'),X('allergies','Allergies','Do you have any medication allergies?','No known medicine allergies.','No known drug allergies.'),X('social','Smoking','Do you smoke?','I smoked a pack a day for 32 years. I quit two years ago.','Former smoker: 32 pack-years, quit 2 years ago.'),X('social','Alcohol','How much alcohol do you drink?','Two beers with dinner on Friday and Saturday.','Four beers weekly.'),X('social','Drugs','Do you use recreational drugs?','No.','No recreational drugs.'),X('social','Work','What do you do now for work?','I drive a delivery van. Unloading boxes is getting difficult.','Delivery driver; limited during unloading.'),X('social','Home and access','Who lives with you and can help with appointments?','I live alone. My daughter can drive me, but I lose pay for weekday visits.','Lives alone; daughter can transport; visits cause lost pay.'),X('family','Family history','What serious illnesses run in your family?','My father died of lung cancer at 68. He smoked too.','Father: lung cancer at 68; father smoked.')],
[R('wheezing','respiratory',True,'Sometimes I hear a whistle when I breathe out.','Intermittent expiratory wheeze.'),R('hemoptysis','respiratory',False,'There has never been blood in the mucus.','No hemoptysis.'),R('sputum','respiratory',True,'The amount and white color have not changed recently.','No recent sputum volume or color change.'),R('fever','general',False,'I have not had fever.','No fever.'),R('weight_loss','general',False,'I have not lost weight.','No weight loss.'),R('night_sweats','general',False,'No drenching night sweats.','No night sweats.'),R('chest_pain','cardiovascular',False,'No chest pain.','No chest pain.'),R('orthopnea','cardiovascular',False,'I lie flat without getting breathless.','No orthopnea.'),R('edema','cardiovascular',False,'My ankles do not swell.','No edema.')],
[E('general_inspect','Comfortable at rest, speaking full sentences.'),E('chest_inspect','Symmetric chest expansion; no accessory muscle use at rest.',['symmetry','accessory muscle use']),E('lungs_auscultate','Breath sounds mildly reduced bilaterally with prolonged expiration and scattered expiratory wheezes; no focal crackles.',['posterior','on skin','compare side to side','mouth open']),E('lungs_percuss','Mildly increased resonance symmetrically over posterior fields.',['posterior','compare side to side']),E('heart_auscultate','Regular rate and rhythm without murmur.'),E('extremities','No peripheral edema, digital clubbing or cyanosis.',['edema','clubbing','cyanosis']),E('osteo_screen','T4 bilateral thoracic paraspinal tissue texture change and tenderness.',['thoracic'],False)],
[D('Chronic obstructive pulmonary disease','D',['hpi_onset','hpi_chronology','history_smoking','exam_lungs_auscultate'],'Chronic productive cough, progressive exertional dyspnea and smoke exposure support COPD; spirometry is needed.'),D('Bronchiectasis','I',['hpi_quality','hpi_past_occurrence'],'Daily sputum and recurrent infections support this alternative; imaging is required and infection history is not proof of cause.'),D('Lung malignancy','N',['hpi_onset','history_smoking','history_family_history'],'Persistent symptoms, age and smoking exposure warrant exclusion despite no hemoptysis or weight loss.')],
['Obtain post-bronchodilator spirometry and chest radiograph; assess symptoms and exacerbation history. If COPD is confirmed, select inhaled bronchodilator therapy and teach technique; review vaccination and continued smoking abstinence. Arrange review in 2 weeks around work. Acute breathlessness, confusion or blue lips needs emergency care.','If sputum/infection history or initial imaging remains concerning, arrange thin-section chest CT and sputum studies when indicated; respiratory referral can guide airway clearance. Explain infection warning signs and avoid empiric long-term antibiotics; review results within 2–4 weeks.','Investigate persistent cough with diagnostic chest imaging and escalate suspicious findings to a lung specialist promptly. Discuss that risk is not a diagnosis and reinforce smoking abstinence; review imaging within 2 weeks and seek earlier care for hemoptysis.'],
[('COPD diagnosis','https://www.nhlbi.nih.gov/health/copd/diagnosis'),('COPD symptoms','https://www.nhlbi.nih.gov/health/copd/symptoms')],
'Distinguish chronic airflow limitation from recurrent suppurative disease and malignancy.','Has breathlessness or sputum changed suddenly, or gradually over months?','I will arrange breathing tests and a chest image rather than assuming the cough is just from past smoking. We will review the results in two weeks. Sudden severe breathing trouble or coughing blood needs earlier help.','We can look for an appointment that limits lost work time and coordinate transport with your daughter if you wish.',vitals={'BP':'132/80 mmHg','P':'82 bpm','R':'18 rpm','T':'98.1 F oral','Pulse Ox':'95% on room air','Ht':'5\' 9"','Wt':'178 lbs'},extra=[X('concern','Patient concern','What worries you about the cough?','My father had lung cancer. I am afraid I have it too.','Concerned about lung cancer.')])

add('msk-shoulder-overuse','Elena Torres',46,'female','Musculoskeletal','Shoulder pain with overhead work','My right shoulder hurts when I reach overhead.',[
H('onset','Onset','When did your shoulder pain start?','About 5 weeks ago after several days painting ceilings.','Five weeks of right shoulder pain after ceiling painting.'),H('location','Location','Where does the shoulder hurt?','On the outer shoulder and the top of my arm.','Lateral shoulder and proximal upper-arm pain.'),H('radiation','Spread','Does the pain go below the elbow?','Sometimes a tingle reaches my thumb when my neck is stiff, but the shoulder ache stays above the elbow.','Shoulder ache remains proximal to elbow; occasional thumb tingling with neck stiffness.'),H('quality','Character','What does the pain feel like?','A dull ache that pinches when I lift the arm.','Aching with pain during elevation.'),H('severity','Severity and function','How bad is the pain?','About 5 out of 10. Reaching shelves and washing my hair hurt.','5/10; limits overhead reach and hair washing.'),H('timing','Pattern','When is the pain worst?','During overhead work and when I lie on that shoulder.','Worse with overhead use and lying on right side.'),H('chronology','Stiffness','Has your movement become stiffer?','It feels a little stiff in the morning but loosens after about 10 minutes.','Morning stiffness approximately 10 minutes.'),H('setting','Injury','Was there a fall or sudden injury?','No fall, pop or sudden pull.','No trauma, pop or acute traction.'),H('aggravating','Neck relationship','Do neck movements change the shoulder pain?','Turning my neck sometimes brings on the thumb tingle, but not the main shoulder pain.','Neck rotation can reproduce thumb tingling, not the principal shoulder pain.'),H('alleviating','Relief','What relieves the shoulder pain?','Resting it and a warm shower help.','Relief with rest and warmth.'),H('treatment','Self-treatment','What have you taken for the pain?','Acetaminophen 500 milligrams once or twice a day on workdays. It helps a little.','Partial relief with acetaminophen 500 mg once or twice on workdays.'),H('past_occurrence','Prior symptoms','Have you had shoulder trouble before?','No previous shoulder trouble. My neck has ached on and off for a year.','No previous shoulder episode; intermittent neck ache for 1 year.')],
[X('pmh','Medical history','What medical conditions do you have?','Type 2 diabetes for 8 years. My last A1c was 7.2 three months ago.','Type 2 diabetes for 8 years; reported A1c 7.2% 3 months ago.'),X('psh','Surgery','What surgery have you had?','A cesarean delivery 18 years ago.','Cesarean delivery 18 years ago.'),X('medications','Medication','What medicines do you take?','Metformin 1000 milligrams twice daily, plus the acetaminophen for this shoulder.','Metformin 1000 mg twice daily; acetaminophen as above.'),X('allergies','Drug reactions','What medication allergies do you have?','Naproxen gave me hives and lip swelling, so I avoid it and other anti-inflammatory pain pills.','Naproxen: hives and lip swelling; avoids NSAIDs.'),X('social','Smoking','Do you smoke?','I never smoked.','Never smoked.'),X('social','Alcohol','Do you drink alcohol?','A glass of wine once or twice a month.','One or two glasses of wine monthly.'),X('social','Drugs','Do you use recreational drugs?','No.','No recreational drugs.'),X('social','Work','What work do you do?','I paint houses. My boss can give me lower-wall work for a while.','House painter; temporary modified duties available.'),X('social','Home','Who helps you at home?','I live with my teenage son. He can help with lifting.','Lives with teenage son; lifting help available.'),X('family','Family history','Does arthritis run in your family?','My mother developed rheumatoid arthritis in her fifties.','Mother: rheumatoid arthritis in her 50s.')],
[R('joint_pain','musculoskeletal',True,'Only this shoulder hurts regularly.','Joint pain limited to the right shoulder.'),R('joint_swelling','musculoskeletal',False,'I have not seen swelling of the shoulder or other joints.','No reported joint swelling.'),R('myalgia','musculoskeletal',False,'No aching all over my muscles.','No generalized myalgia.'),R('numbness','neurologic',False,'No constant numbness.','No persistent numbness.'),R('tingling','neurologic',True,'The thumb tingle is brief, only now and then.','Intermittent brief thumb paresthesia.'),R('weakness','neurologic',False,'I can grip normally. Lifting hurts rather than feeling powerless.','No grip weakness; elevation pain-limited.'),R('fever','general',False,'No fever.','No fever.'),R('weight_loss','general',False,'My weight is unchanged.','No weight loss.'),R('fatigue','general',False,'I am not unusually tired.','No unusual fatigue.')],
[E('general_inspect','Alert and comfortable at rest.'),E('msk_inspect','No shoulder deformity, erythema or visible swelling.',['swelling','deformity','erythema']),E('msk_palpate','Tenderness over the right greater tuberosity and lateral shoulder; no acromioclavicular point tenderness.',['point tenderness']),E('msk_rom','Right active shoulder elevation painful from 70 to 120 degrees; passive flexion nearly full with mild end-range discomfort. External rotation mildly limited by discomfort; left shoulder motion full.',['flexion','rotation']),E('msk_strength','Right shoulder elevation and external rotation 4+/5 with pain; elbow, wrist and grip strength 5/5 bilaterally.',['upper extremity']),E('neck_rom','Mildly reduced cervical rotation to the right with neck discomfort.',['rotation']),E('neuro_sensory','Light touch intact in both upper limbs, including thumbs.',['light touch']),E('heart_auscultate','Regular rate and rhythm without murmur.'),E('lungs_auscultate','Clear bilateral breath sounds.',['posterior','on skin','compare side to side','mouth open']),E('osteo_screen','C5 right paraspinal tissue texture change and tenderness.',['cervical'],False)],
[D('Rotator cuff tendinopathy from overuse','T',['hpi_onset','hpi_timing','exam_msk_rom'],'Overhead overuse, lateral pain and pain-limited active elevation support tendinopathy.'),D('Cervical degenerative radiculopathy','D',['hpi_radiation','hpi_aggravating','exam_neck_rom'],'Neck-related thumb tingling supports a possible cervical contributor; normal distal examination lowers immediate concern.'),D('Early adhesive capsulitis','I',['history_medical_history','hpi_chronology','exam_msk_rom'],'Diabetes and stiffness allow early capsulitis, but near-preserved passive motion makes it less likely than tendinopathy.')],
['Use temporary modified overhead duties and a physical-therapy/home mobility program; acetaminophen is an option after safe-dose review. Avoid NSAIDs pending allergy assessment because of hives/lip swelling. Reassess in 3 weeks; consider radiograph or ultrasound for persistent pain or objective weakness. New weakness, fever or a hot swollen joint needs earlier assessment.','If neck/arm symptoms persist, repeat focused neurologic assessment and consider cervical imaging/referral if deficits or progression develop. Explain safe work posture and gentle mobility; reassess with the shoulder in 3 weeks.','If passive stiffness progresses, reassess for capsulitis and discuss stretching/physical therapy; consider specialist-guided injection with glucose counseling if indicated. Review diabetes management and explain how to monitor progressive stiffness.'],
[('Shoulder pain and common shoulder problems','https://www.orthoinfo.org/diseases--conditions/shoulder-pain-and-common-shoulder-problems/'),('Rotator cuff tears','https://www.orthoinfo.org/diseases--conditions/rotator-cuff-tears')],
'Compare active and passive motion while checking neurologic symptoms and medication safety.','Is movement limited by pain, by weakness, or even when someone else moves the arm?','We will reduce overhead strain and start a gentle rehabilitation plan. Because naproxen caused hives and lip swelling, I will not assume another anti-inflammatory pill is safe. We will reassess in three weeks.','Modified work can help protect your income while the shoulder recovers. Persistent weakness or increasing stiffness would change the next steps.')

add('msk-knee-injury','Graham Wilson',54,'male','Musculoskeletal','Knee pain after twisting','My right knee has been sore and swollen since I twisted it.',[
H('onset','Onset','When did the knee pain start?','Three days ago.','Right knee pain for 3 days.'),H('setting','Mechanism','How did you hurt the knee?','I turned while carrying a box, with my right foot planted. I did not fall.','Twisting injury on a planted foot while carrying a box; no fall.'),H('location','Location','Where is the pain?','Along the inside of my right knee.','Medial right knee pain.'),H('radiation','Spread','Does the pain spread?','No, it stays around the knee.','No radiation.'),H('quality','Character','What does it feel like?','An ache with a sharp catch if I turn.','Aching with catching pain during rotation.'),H('severity','Weight bearing','Can you walk on it?','I can walk with a limp. The pain is 6 out of 10.','Weight bearing with limp; pain 6/10.'),H('chronology','Swelling','When did the swelling develop?','It swelled gradually that evening, not immediately.','Delayed swelling over the first evening.'),H('timing','Catching, locking or giving way','Does the knee lock or give way?','It catches, but I can straighten it. It has not given way.','Catching without true locking or giving way.'),H('aggravating','Triggers','What makes it worse?','Turning, stairs and deep bending.','Worse with twisting, stairs and deep flexion.'),H('alleviating','Relief','What helps?','Rest, ice wrapped in a towel, and elevating it.','Relief with rest, protected ice and elevation.'),H('treatment','Medication','What have you taken for the knee?','Acetaminophen 650 milligrams twice yesterday.','Acetaminophen 650 mg twice yesterday.'),H('past_occurrence','Prior joint trouble','Did the knee bother you before this injury?','It sometimes ached after work and felt stiff for about 5 minutes in the morning.','Prior activity-related ache and brief morning stiffness.')],
[X('pmh','Medical history','What medical conditions do you have?','High blood pressure and gout. I had one red, swollen big toe last year, confirmed with fluid testing.','Hypertension; crystal-confirmed gout episode last year.'),X('psh','Surgery','Have you had knee surgery or other operations?','No knee surgery. I had a hernia repaired at 30.','Hernia repair at 30; no knee surgery.'),X('medications','Daily medicines','What daily medicines do you take?','Hydrochlorothiazide 25 milligrams daily. No regular gout medicine.','Hydrochlorothiazide 25 mg daily; no urate-lowering therapy.'),X('allergies','Drug reactions','Are you allergic to any medicines?','No known drug allergies.','No known drug allergies.'),X('social','Smoking','Do you smoke?','I smoked half a pack daily for 10 years and quit 15 years ago.','Former smoker: 5 pack-years, quit 15 years ago.'),X('social','Alcohol','How much alcohol do you drink?','Usually three beers on Friday and three on Saturday.','Approximately six beers weekly.'),X('social','Drugs','Do you use recreational drugs?','No.','No recreational drugs.'),X('social','Work','What does your work involve?','I move stock in a grocery store, including lifting and squatting.','Grocery stocker; frequent lifting and squatting.'),X('social','Home','Who is available to help you?','My wife can help. We have one flight of stairs at home.','Lives with wife; one flight of home stairs.'),X('family','Family history','Does joint disease run in the family?','My mother had knee replacements for wear-and-tear arthritis.','Mother: knee osteoarthritis requiring replacement.')],
[R('joint_swelling','musculoskeletal',True,'The right knee is swollen.','Right knee swelling.'),R('joint_pain','musculoskeletal',True,'No other joint hurts right now.','No other current joint pain.'),R('myalgia','musculoskeletal',False,'No muscle aches elsewhere.','No generalized myalgia.'),R('fever','general',False,'No fever.','No fever.'),R('chills','general',False,'No chills.','No chills.'),R('fatigue','general',False,'I do not feel ill or unusually tired.','No systemic malaise.'),R('numbness','neurologic',False,'My foot is not numb.','No distal numbness.'),R('tingling','neurologic',False,'No pins and needles.','No paresthesias.'),R('weakness','neurologic',False,'The ankle and foot feel normally strong.','No distal weakness.')],
[E('general_inspect','Alert, comfortable at rest.'),E('msk_inspect','Small right knee effusion without erythema or deformity.',['swelling','erythema','deformity']),E('msk_palpate','Medial joint-line tenderness and mild warmth; no patellar or fibular-head tenderness.',['point tenderness']),E('msk_rom','Right knee extends to 0 degrees and flexes to 110 degrees with pain near end flexion; mild crepitus.',['flexion','extension']),E('msk_strength','Knee extension 4+/5 limited by pain; ankle dorsiflexion and plantarflexion 5/5.',['lower extremity']),E('gait','Antalgic gait; able to take four steps.'),E('peripheral_pulses','Dorsalis pedis and posterior tibial pulses 2+ bilaterally.',['dorsalis pedis','posterior tibial']),E('heart_auscultate','Regular rate and rhythm without murmur.'),E('lungs_auscultate','Clear bilateral breath sounds.',['posterior','on skin','compare side to side','mouth open']),E('osteo_screen','L4 right lumbar paraspinal tissue texture change and tenderness.',['lumbar'],False)],
[D('Medial meniscal injury','T',['hpi_setting','hpi_timing','exam_msk_palpate'],'Twisting mechanism, delayed effusion, medial joint-line tenderness and catching favor a meniscal injury.'),D('Knee osteoarthritis with an acute flare','D',['hpi_past_occurrence','history_family_history','exam_msk_rom'],'Prior activity-related ache, brief stiffness and crepitus support underlying osteoarthritis.'),D('Acute gouty arthritis','E',['history_medical_history','history_daily_medicines','exam_msk_palpate'],'Prior crystal-proven gout, diuretic exposure and a warm effusion make crystal arthritis plausible, although this episode followed mechanical injury.')],
['Protect weight bearing as needed, avoid twisting/squatting and use ice, compression and elevation with safe analgesia. Assess fracture-imaging criteria and ligament stability; consider right knee MRI or orthopedics for persistent catching or true locking. Arrange modified work and review in 1 week. Fever, marked warmth, inability to bear weight or a locked knee warrants urgent reassessment.','If chronic symptoms persist, obtain weight-bearing radiographs when indicated and discuss strengthening/physical therapy and activity modification. Explain that degenerative changes may coexist with injury; reassess after the acute swelling improves in 2–3 weeks.','If crystal or septic arthritis remains possible with increasing warmth/effusion, arrange aspiration for crystals, cell count and culture before assuming gout. Review diuretic and gout management and safe anti-inflammatory options; explain that crystals do not exclude infection, with same-day evaluation for a hot swollen joint or fever.'],
[('Meniscus tears','https://www.orthoinfo.org/diseases--conditions/meniscus-tears')],
'Use mechanism and mechanical symptoms while retaining crystal and infection safety checks.','Was swelling immediate or delayed, and is the knee truly locked?','We will protect the knee, assess stability and decide whether imaging is needed. I want to review it in one week. If it becomes hot and very swollen, you develop fever, or it locks, seek urgent assessment.','We can document temporary lifting and squatting limits and discuss how you will manage stairs at home.')

add('msk-hand-stiffness','Amina Reed',38,'female','Musculoskeletal','Persistent hand stiffness and swelling','Both hands are stiff and swollen when I wake up.',[
H('onset','Onset','When did the hand symptoms start?','About 8 weeks ago.','Eight weeks of bilateral hand symptoms.'),H('location','Joints','Which joints are affected?','The knuckles where my fingers meet my hands and the middle finger joints, on both sides.','Bilateral MCP and PIP symptoms.'),H('quality','Character','How do the hands feel?','Achy, puffy and hard to bend.','Aching, swelling and stiffness.'),H('severity','Function','How is this affecting you?','It is about 5 out of 10. Opening jars and fastening buttons are difficult.','5/10; difficulty with jars and buttons.'),H('timing','Morning stiffness','How long does the morning stiffness last?','At least an hour, sometimes an hour and a half.','Morning stiffness 60–90 minutes.'),H('chronology','Progression','Has it improved or worsened?','It started in a few fingers and now affects both hands most days.','Progressed from several fingers to bilateral daily symptoms.'),H('setting','Preceding illness','Were you sick before it started?','I had a mild cold just before it began. A child at the daycare had a slapped-cheek rash.','A mild cold preceded the joint symptoms. A child at the daycare had a slapped-cheek rash.'),H('aggravating','Rest','What makes the stiffness worse?','Sitting still for a long time makes me stiff again.','Stiffness after inactivity.'),H('alleviating','Relief','What helps your hands?','A warm shower and gently moving them.','Relief with warmth and movement.'),H('treatment','Self-treatment','Have you tried pain medicine?','Ibuprofen 200 milligrams twice on a few days helped somewhat, but it upset my stomach.','Partial relief but dyspepsia with intermittent ibuprofen 200 mg twice daily.'),H('past_occurrence','Previous episodes','Has this happened before?','No, not like this.','No similar previous episode.')],
[X('pmh','Medical history','What medical problems do you have?','I have hypothyroidism, treated for 6 years.','Hypothyroidism for 6 years.'),X('psh','Surgery','What surgery have you had?','My gallbladder was removed 4 years ago.','Cholecystectomy 4 years ago.'),X('medications','Medicines','What medications do you take?','Levothyroxine 75 micrograms every morning, and the occasional ibuprofen I mentioned.','Levothyroxine 75 mcg daily; intermittent ibuprofen.'),X('allergies','Drug reactions','Do you have medication allergies?','Amoxicillin caused hives as an adult, without breathing trouble.','Amoxicillin: hives without respiratory symptoms.'),X('social','Smoking','Do you smoke?','I have never smoked.','Never smoked.'),X('social','Alcohol','Do you drink alcohol?','I do not drink.','No alcohol.'),X('social','Drugs','Do you use recreational drugs?','No.','No recreational drugs.'),X('social','Work','What do you do for work?','I work at a daycare, lifting children and opening food containers.','Daycare worker; hand function affects lifting and containers.'),X('social','Support','Who helps at home?','My partner helps with our toddler, but missing work for appointments is difficult.','Partner helps with toddler; appointment-related work absence is difficult.'),X('family','Family history','Is there arthritis in your family?','My mother has rheumatoid arthritis. My father has arthritis in his finger tips.','Mother: rheumatoid arthritis; father: distal finger arthritis.'),X('obgyn','Pregnancy','Could you be pregnant?','My period was one week ago. I use condoms and have not done a pregnancy test.','LMP 1 week ago; condoms; pregnancy test not obtained.')],
[R('joint_swelling','musculoskeletal',True,'The same finger joints look puffy on both hands.','Symmetric finger-joint swelling.'),R('joint_pain','musculoskeletal',True,'My wrists ache too.','Associated wrist arthralgia.'),R('myalgia','musculoskeletal',False,'My muscles themselves do not ache.','No myalgia.'),R('fatigue','general',True,'I feel more tired than usual.','Fatigue.'),R('fever','general',False,'No fever.','No fever.'),R('weight_loss','general',False,'No weight loss.','No weight loss.'),R('rash','skin',False,'I have not had a rash or scaly patches.','No rash or psoriasis-like plaques.'),R('photosensitivity','skin',False,'Sunlight does not cause a rash.','No photosensitive rash.'),R('nail_changes','skin',False,'I have not noticed pits or changes in my nails.','No nail changes.')],
[E('general_inspect','Alert, mildly tired appearing.'),E('msk_inspect','Symmetric swelling of second and third MCP and PIP joints; no DIP swelling or deformity.',['swelling','deformity']),E('msk_palpate','Boggy tenderness of affected MCP/PIP joints and mild bilateral wrist tenderness.',['point tenderness']),E('msk_rom','Finger flexion limited by pain and swelling; wrist flexion mildly painful bilaterally.',['flexion','extension']),E('msk_strength','Grip strength mildly reduced bilaterally by pain; proximal arm strength 5/5.',['upper extremity']),E('skin_inspect','No rash on inspected arms or palms; no nail pitting.',['arms','palms']),E('heart_auscultate','Regular rate and rhythm without murmur.'),E('lungs_auscultate','Clear bilateral breath sounds.',['posterior','on skin','compare side to side','mouth open']),E('osteo_screen','T1 bilateral paraspinal tissue texture change and tenderness.',['thoracic'],False)],
[D('Rheumatoid arthritis','A',['hpi_timing','history_family_history','exam_msk_palpate'],'Persistent symmetric small-joint synovitis and prolonged morning stiffness favor RA.'),D('Viral polyarthritis, including parvovirus B19','I',['hpi_setting','exam_msk_inspect'],'Exposure and preceding illness support viral arthritis; persistence for 8 weeks makes reassessment essential.'),D('Hand osteoarthritis','D',['history_family_history','hpi_severity'],'Hand functional pain and family history support consideration, but MCP synovitis and prolonged stiffness weigh against primary OA.')],
['Arrange urgent rheumatology referral for persistent small-joint synovitis; do not wait for laboratory results. Obtain RF, anti-CCP, CBC, renal/liver profile and ESR/CRP, with hand/foot imaging as appropriate. Discuss early disease-modifying treatment assessment, joint protection and safe symptom relief; review within 1–2 weeks to confirm access. A hot single joint or fever needs urgent evaluation.','Assess whether parvovirus testing would clarify the exposure and prolonged course; avoid attributing persistent synovitis to a past cold alone. Offer supportive analgesia and explain pregnancy/exposure discussion if relevant; review results in 1–2 weeks alongside rheumatology referral.','If degenerative disease remains after inflammatory assessment, consider radiographs and occupational therapy for hand function, pacing and adaptive aids. Explain that symptomatic measures do not replace evaluation of synovitis; reassess functional needs in 2–4 weeks.'],
[('Rheumatoid arthritis diagnosis and treatment','https://www.niams.nih.gov/health-topics/rheumatoid-arthritis/diagnosis-treatment-and-steps-to-take')],
'Recognize persistent inflammatory small-joint disease and refer without waiting for tests.','How long does stiffness last, and are the swollen joints symmetric?','The swelling and long morning stiffness need prompt assessment by a joint specialist. We can arrange blood tests, but the referral should not wait for their results. We will check within one to two weeks that you have an appointment.','We can discuss scheduling and a work note, plus practical tools that make buttons and jars easier while the assessment is underway.')

add('heent-ear-pain','Jordan Park',24,'male','HEENT','Ear pain after swimming','My left ear hurts and feels blocked.',[
H('onset','Onset','When did the ear pain begin?','Two days ago.','Left otalgia for 2 days.'),H('location','Side','Which ear hurts?','The left one, near the opening.','Pain at left canal opening.'),H('quality','Character','What does the ear pain feel like?','A steady sore ache with itching.','Aching and pruritus.'),H('severity','Severity','How bad is the pain?','About 5 out of 10.','Pain 5/10.'),H('timing','Pattern','Is it constant or intermittent?','It is there most of the day.','Persistent daily discomfort.'),H('chronology','Change','How has it changed?','The itching started first, then it became sore and muffled.','Pruritus preceded pain and muffled hearing.'),H('setting','Water and ear products','Have you been swimming or put anything new in your ear?','I swam all weekend and started using new in-ear earbuds last week.','Recent swimming and new in-ear earbuds.'),H('aggravating','Triggers','What makes the pain worse?','Touching the ear and putting the earbud in hurt. Chewing aches a little near my jaw.','Pain with ear contact/earbud insertion; mild chewing-related jaw ache.'),H('alleviating','Relief','What helps?','Leaving the earbud out helps a little.','Partial relief without earbud.'),H('treatment','Self-treatment','Have you used drops or pain medicine?','I took acetaminophen 500 milligrams last night. No ear drops.','Acetaminophen 500 mg once; no ear drops.'),H('past_occurrence','Prior ear trouble','Have you had this before?','Not ear pain, but earbuds have made my skin itchy before.','Prior earbud-related itching, no prior otalgia.')],
[X('pmh','Medical history','Do you have chronic illnesses?','No chronic illness. I grind my teeth at night.','No chronic illness; nocturnal bruxism.'),X('psh','Ear procedures','Have you had ear surgery or a perforated eardrum?','No tubes, ear surgery or known hole in my eardrum.','No ear surgery, tympanostomy or known perforation.'),X('medications','Medication','What medicines do you usually take?','No regular medicine.','No regular medication.'),X('allergies','Drug reactions','Are you allergic to medicines?','Neomycin ointment made my skin red and itchy.','Neomycin: pruritic erythematous skin reaction.'),X('social','Smoking','Do you smoke or vape?','I have never smoked or vaped.','Never smoked or vaped.'),X('social','Alcohol','How much alcohol do you drink?','One or two beers on a weekend.','One or two beers weekly.'),X('social','Drugs','Do you use recreational drugs?','No.','No recreational drugs.'),X('social','Work','What do you do for work?','I am a lifeguard and wear earbuds during my commute.','Lifeguard; earbud use during commute.'),X('social','Home','Who lives with you?','I live with my brother.','Lives with brother.'),X('family','Family history','Is there hearing loss in your family?','My father needed hearing aids in his sixties.','Father: hearing loss requiring aids in his 60s.')],
[R('hearing_loss','heent',True,'Sounds are muffled on the left.','Muffled left hearing.'),R('ear_discharge','heent',True,'There was a little clear fluid on my pillow.','Small clear left ear discharge.'),R('sore_throat','heent',False,'No sore throat.','No sore throat.'),R('fever','general',False,'No fever.','No fever.'),R('chills','general',False,'No chills.','No chills.'),R('fatigue','general',False,'I feel well apart from the ear.','No systemic malaise.'),R('dizziness','neurologic',False,'No spinning or dizziness.','No vertigo.'),R('headache','neurologic',False,'No headache.','No headache.'),R('weakness','neurologic',False,'No weakness in my face.','No facial weakness.')],
[E('general_inspect','Alert, well appearing.'),E('heent_ears','Left tragal/pinna manipulation tender; canal erythematous and edematous with scant debris. Left tympanic membrane visualized and intact without bulging. Right canal without erythema or edema; right membrane intact and nonbulging; no mastoid tenderness.',['right ear','left ear']),E('msk_palpate','Mild left temporomandibular joint tenderness with jaw opening; no facial swelling.',['point tenderness']),E('lymph_nodes','No enlarged or tender cervical nodes.',['cervical']),E('heent_throat','Oropharynx without erythema or exudate.',['oropharynx']),E('heart_auscultate','Regular rate and rhythm without murmur.'),E('lungs_auscultate','Clear bilateral breath sounds.',['posterior','on skin','compare side to side','mouth open']),E('osteo_screen','C2 left paraspinal tissue texture change and tenderness.',['cervical'],False)],
[D('Acute otitis externa','I',['hpi_setting','exam_heent_ears'],'Water exposure, tragal tenderness and inflamed canal support otitis externa.'),D('Allergic contact dermatitis of the ear canal','A',['hpi_setting','hpi_past_occurrence','history_drug_reactions'],'New earbuds, prior contact itching and skin allergy support a contact contributor; marked canal pain/debris favor infection.'),D('Temporomandibular disorder with referred ear pain','T',['history_medical_history','hpi_aggravating','exam_msk_palpate'],'Bruxism and jaw tenderness support a coexisting referred component but do not explain canal inflammation.')],
['Treat with appropriate topical otic therapy and analgesia after membrane review; avoid neomycin given the skin reaction. Teach drop administration and keep the ear dry, avoiding earbuds and swabs. Reassess if not improving within 48–72 hours. Fever, spreading swelling, severe worsening pain or new facial weakness needs prompt evaluation.','Remove the new earbud exposure and avoid unnecessary topical sensitizers. If dermatitis persists after infection treatment, consider ENT/dermatology assessment and guided topical anti-inflammatory treatment; explain that contact allergy is not confirmed by itching alone.','Reduce gum chewing and clenching; discuss gentle jaw care and dental assessment for persistent symptoms. Use safe analgesia if needed and explain that jaw treatment does not replace treatment of the inflamed canal.'],
[('Acute otitis externa clinical practice guideline','https://www.entnet.org/quality-practice/quality-products/clinical-practice-guidelines/aoe/')],
'Distinguish canal disease from referred ear pain and choose safe topical therapy.','Does touching the outer ear hurt, and is there discharge or jaw-related pain?','The ear examination will guide treatment. If canal infection is confirmed, drops and keeping the ear dry usually help. We will avoid neomycin because of your reaction. Come back if it is not improving within two to three days.','We can discuss temporary dry duties at the pool so the ear can recover without unnecessary time off.')

add('heent-sore-throat','Priya Shah',31,'female','HEENT','Sore throat with nasal symptoms','My throat is scratchy and sore, and my nose keeps running.',[
H('onset','Onset','When did the sore throat start?','Four days ago.','Four days of sore throat; rhinorrhea began 1 day earlier.'),H('location','Location','Where does the throat hurt?','Across the back, on both sides.','Bilateral posterior throat discomfort.'),H('quality','Character','How does it feel?','Scratchy and raw, not like something is stuck.','Scratchy/raw sensation without foreign-body sensation.'),H('severity','Swallowing','Can you eat and drink?','Yes. Swallowing stings about 4 out of 10, but I can drink normally.','Odynophagia 4/10; normal oral fluid intake.'),H('timing','Pattern','When is the throat irritation worst?','In the morning and toward the end of a cleaning shift.','Worse in mornings and at end of cleaning shifts.'),H('chronology','Change','Has it been getting worse?','It is about the same. My runny nose started a day earlier.','Stable sore throat; rhinorrhea preceded it by 1 day.'),H('setting','Contacts and exposure','Any sick contacts or new fumes?','My daughter had a cold. At work we switched to a strong spray cleaner last week, and it stings my throat.','Daughter with URI; new workplace spray cleaner temporally provokes irritation.'),H('aggravating','Other triggers','Does anything else bother your nose or throat?','Dust and pollen make me sneeze and make my eyes itch.','Dust/pollen-associated sneezing and ocular itching.'),H('alleviating','Relief','What helps?','Warm tea and being away from the cleaning spray.','Relief with warm fluids and avoiding spray.'),H('treatment','Self-treatment','What have you taken for it?','One acetaminophen 500-milligram tablet yesterday. I have not taken antibiotics.','Acetaminophen 500 mg once; no antibiotics.'),H('past_occurrence','Past pattern','Have you had similar symptoms before?','I get seasonal sneezing, but the throat is sorer this time.','Seasonal rhinitis history; greater throat discomfort now.')],
[X('pmh','Medical history','What medical conditions do you have?','Seasonal allergies. No other chronic illness.','Seasonal allergic rhinitis; no other chronic illness.'),X('psh','Surgery','Have you had any operations?','No operations.','No surgical history.'),X('medications','Medicine','What medicines do you take?','Loratadine 10 milligrams when allergies bother me, but none this week.','Loratadine 10 mg as needed; none this week.'),X('allergies','Drug reactions','Do you have drug allergies?','No known medication allergies.','No known drug allergies.'),X('social','Smoking','Do you smoke or vape?','I have never smoked or vaped.','Never smoked or vaped.'),X('social','Alcohol','Do you drink alcohol?','No alcohol.','No alcohol.'),X('social','Drugs','Do you use recreational drugs?','No.','No recreational drugs.'),X('social','Work','What work do you do?','I clean offices. Some rooms have poor ventilation.','Office cleaner; variable ventilation.'),X('social','Home','Who lives with you?','My husband and our six-year-old daughter.','Lives with husband and 6-year-old daughter.'),X('family','Family history','Do allergies or asthma run in your family?','My sister has hay fever and my father has asthma.','Sister: allergic rhinitis; father: asthma.')],
[R('cough','respiratory',True,'I have a mild dry cough.','Mild dry cough.'),R('dyspnea','respiratory',False,'No trouble breathing.','No dyspnea.'),R('wheezing','respiratory',False,'No wheezing.','No wheeze.'),R('rhinorrhea','heent',True,'My nose runs clear fluid.','Clear rhinorrhea.'),R('hoarseness','heent',True,'My voice is a little hoarse.','Mild hoarseness.'),R('ear_pain','heent',False,'My ears do not hurt.','No otalgia.'),R('fever','general',False,'I have not measured a fever.','No reported fever.'),R('fatigue','general',True,'I am a little tired.','Mild fatigue.'),R('chills','general',False,'No chills.','No chills.')],
[E('general_inspect','Well appearing, handling secretions and speaking comfortably.'),E('heent_throat','Mild diffuse pharyngeal erythema with posterior cobblestoning; no tonsillar exudate, asymmetry or uvular deviation. Mouth opens normally.',['tongue blade','oropharynx','tonsils']),E('heent_nose','Bilateral pale mildly edematous turbinates with clear secretions.',['right naris','left naris']),E('lymph_nodes','No tender anterior cervical lymphadenopathy.',['cervical']),E('heent_ears','Both tympanic membranes intact and nonbulging.',['right ear','left ear']),E('heart_auscultate','Regular rate and rhythm without murmur.'),E('lungs_auscultate','Clear bilateral breath sounds without wheeze.',['posterior','on skin','compare side to side','mouth open']),E('osteo_screen','C3 bilateral paraspinal tissue texture change and tenderness.',['cervical'],False)],
[D('Viral pharyngitis','I',['hpi_onset','hpi_setting','symptom_cough','symptom_hoarseness'],'Acute URI exposure, rhinorrhea, cough and nonexudative throat support a viral illness.'),D('Allergic rhinitis with postnasal throat irritation','A',['hpi_aggravating','history_medical_history','exam_heent_nose'],'Seasonal itching/sneezing, pale turbinates and cobblestoning support allergic contribution.'),D('Inhalational irritant pharyngitis','I2',['hpi_setting','hpi_timing','hpi_alleviating'],'New spray exposure with work-related worsening and relief away supports irritant contribution.')],
['Provide fluids and appropriate analgesia, and discuss infection-control measures. Clear viral features do not require routine streptococcal testing or antibiotics; test if the clinical pattern changes. Reassess if not improving within 5–7 days. Drooling, breathing difficulty, neck swelling or inability to swallow fluids needs urgent evaluation.','Resume appropriate rhinitis treatment, considering intranasal corticosteroid or a nonsedating antihistamine after review; teach spray technique and reduce identified allergen exposure. Explain that allergy may coexist with a cold and that antibiotics do not treat allergy.','Avoid direct aerosol inhalation, improve ventilation and review the product safety instructions with occupational health; do not mix cleaners. Consider safer work practices/products and explain prompt assessment for chest tightness or respiratory symptoms.'],
[('CDC group A streptococcal pharyngitis guidance','https://www.cdc.gov/group-a-strep/hcp/clinical-guidance/strep-throat.html')],
'Use viral, allergic and exposure clues without reflex antibiotic treatment.','Are symptoms linked to a cold contact, itching/sneezing, or a workplace exposure?','The history and examination can help distinguish a cold, allergy and irritation from the new spray. We can relieve the soreness and reduce exposures. If drinking or breathing becomes difficult, seek urgent care.','We can discuss ventilation and a safer cleaning method with your workplace, with your permission.',extra=[X('pertinent_negative','Airway warning symptoms','Are you drooling, unable to open your mouth, or unable to swallow liquids?','No. I can open my mouth and swallow liquids without drooling.','No drooling, trismus or inability to swallow liquids.')])

add('skin-contact-rash','Tessa Morgan',29,'female','Skin','Itchy rash beneath a wristwatch','I have an itchy rash where my watch sits.',[
H('onset','Onset','When did the rash start?','About 6 days ago.','Six days of localized wrist rash.'),H('location','Distribution','Where is the rash?','On the inside of my left wrist, right under the watch.','Volar left wrist under watch.'),H('quality','Sensation','What does it feel like?','Itches and burns a little.','Pruritic with mild burning.'),H('severity','Severity','How bothersome is the itch?','About 6 out of 10. It woke me once last night.','Itch 6/10 with one nocturnal awakening.'),H('timing','Persistence','Does it come and go within a day?','No, the patch stays there all day.','Persistent patch rather than transient wheals.'),H('chronology','Progression','Has it spread?','It got bigger under the strap but has not spread elsewhere.','Enlarged within contact area; no distant spread.'),H('setting','New exposure','What changed before the rash?','I started wearing a metal-backed watch 10 days ago. I leave it on when washing my hands at work.','New metal-backed watch 10 days ago; wet exposure under strap.'),H('aggravating','Triggers','What makes it worse?','Sweat, soap trapped under it and wearing the watch.','Worse with sweat, trapped soap and watch contact.'),H('alleviating','Relief','What helps?','Taking the watch off and a cool cloth.','Improves without watch and with cool compress.'),H('treatment','Self-treatment','Have you used any creams?','Only fragrance-free moisturizer. No steroid or antibiotic cream.','Fragrance-free emollient only.'),H('past_occurrence','Previous skin reaction','Have you reacted to jewelry before?','Cheap earrings made my earlobes itch years ago.','Prior earring-associated pruritus.')],
[X('pmh','Skin history','Have you had eczema or other skin problems?','Mild eczema as a child, but no regular rash now.','Childhood eczema.'),X('psh','Surgery','What surgery have you had?','My appendix was removed when I was 16.','Appendectomy at 16.'),X('medications','Medication','What medicines do you take?','An oral contraceptive daily. No new medicines in the last three months.','Daily oral contraceptive; no new medication in 3 months.'),X('allergies','Drug reactions','Do you have medication allergies?','No known drug allergies.','No known drug allergies.'),X('social','Smoking','Do you smoke?','I do not smoke or vape.','No smoking or vaping.'),X('social','Alcohol','How much alcohol do you drink?','Two glasses of wine a week.','Two glasses of wine weekly.'),X('social','Drugs','Do you use recreational drugs?','No.','No recreational drugs.'),X('social','Work','What does your work involve?','I am a food-service worker and wash my hands often.','Food-service work with frequent handwashing.'),X('social','Home and contacts','Does anyone you live with have a rash?','My roommate had ringworm on her arm last month. We sometimes share towels.','Roommate had ringworm last month; occasional towel sharing.'),X('family','Family history','Does eczema run in your family?','My sister has eczema.','Sister: eczema.')],
[R('rash','skin',True,'Only the patch on my wrist.','Localized wrist rash.'),R('pruritus','skin',True,'It is itchy more than painful.','Pruritus predominates.'),R('skin_drainage','skin',False,'No pus or drainage.','No drainage.'),R('fever','general',False,'No fever.','No fever.'),R('chills','general',False,'No chills.','No chills.'),R('fatigue','general',False,'I feel well.','No malaise.'),R('dyspnea','respiratory',False,'No trouble breathing.','No dyspnea.'),R('wheezing','respiratory',False,'No wheezing.','No wheeze.'),R('cough','respiratory',False,'No cough.','No cough.')],
[E('general_inspect','Well appearing; no respiratory distress.'),E('skin_inspect','Volar left wrist: 3 by 4 cm erythematous scaly plaque with small papules and superficial excoriations, matching watch-back/strap contact. No annular raised border, central clearing, purulence or spreading erythema. No rash on the other inspected arm or palms.',['arms','palms']),E('msk_palpate','Wrist skin mildly tender without marked warmth or fluctuance; no joint tenderness.',['point tenderness']),E('lymph_nodes','No left axillary lymphadenopathy.',['axillary']),E('heart_auscultate','Regular rate and rhythm without murmur.'),E('lungs_auscultate','Clear bilateral breath sounds.',['posterior','on skin','compare side to side','mouth open']),E('osteo_screen','T2 left thoracic paraspinal tissue texture change and tenderness.',['thoracic'],False)],
[D('Allergic contact dermatitis, suspected metal exposure','A',['hpi_setting','hpi_past_occurrence','exam_skin_inspect'],'Contact distribution and prior jewelry reaction support allergic dermatitis; specific allergen not confirmed.'),D('Irritant contact dermatitis','I2',['hpi_aggravating','history_work'],'Frequent wet work and trapped soap/sweat provide an independent irritant mechanism.'),D('Tinea corporis','I',['history_home_and_contacts','exam_skin_inspect'],'Household fungal exposure and a scaly plaque make tinea possible; absent annular edge/central clearing lowers likelihood.')],
['Stop wearing the watch; use gentle skin care, emollient and a short appropriate topical corticosteroid course if fungal infection is not suspected on assessment. Discuss avoiding likely metal contact and patch testing if recurrent. Review in 1–2 weeks; seek earlier care for spreading redness, marked pain, pus or fever.','Reduce prolonged wet/soap contact and dry beneath accessories; review workplace skin protection and substitute a less irritating routine. Use barrier emollient and explain that multiple contact mechanisms may coexist; seek occupational-health or dermatology input if work-associated dermatitis persists despite protection.','If morphology or lack of response raises concern, perform skin scraping/KOH before continuing steroid alone; use topical antifungal if confirmed or strongly suspected. Avoid shared towels and explain that routine antibiotics are not indicated.'],
[('Nickel allergy','https://www.aad.org/public/diseases/eczema/insider/nickel-allergy'),('Contact dermatitis patterns','https://www.aad.org/public/everyday-care/itchy-skin/rash/itchy-rash-contact-dermatitis')],
'Describe morphology and distribution, then distinguish contact mechanisms from infection.','Is the rash confined to contact with a product, and are there competing wet-work or fungal exposures?','The examination will look at the shape and surface of the rash. Remove the watch for now and use gentle skin care. We may need a skin scraping if fungus is possible, because treatments differ.','We can suggest a handwashing and skin-protection routine that fits food-safety rules at work.',extra=[X('pertinent_negative','Severe reaction symptoms','Any swelling of the lips or tongue or blisters in the mouth?','No swelling and no mouth blisters.','No angioedema or mucosal lesions.')])

add('skin-localized-redness','Owen Price',42,'male','Skin','Expanding painful redness on the leg','A red sore patch on my left shin is getting bigger.',[
H('onset','Onset','When did you notice the red area?','Two days ago.','Expanding left shin erythema for 2 days.'),H('location','Location','Where did it begin?','Around a small scratch on the front of my left shin.','Began around anterior left shin scratch.'),H('quality','Sensation','What does it feel like?','Warm and sore, more painful than itchy.','Warmth and tenderness predominate over itch.'),H('severity','Severity','How bad is the pain?','About 4 out of 10. I can walk normally.','4/10; normal reported walking ability.'),H('timing','Pattern','Is the pain constant?','It is a steady soreness.','Steady discomfort.'),H('chronology','Spread','How has the patch changed?','It was coin-sized and is now about the size of my palm.','Expanded from coin-sized to palm-sized.'),H('setting','Injury and exposure','How did you get the scratch?','A branch scraped me while gardening. Mosquitoes were around, but I did not see a bite there.','Gardening scratch; insect exposure without witnessed bite at site.'),H('aggravating','Triggers','What makes it worse?','Touching it and standing all day.','Worse with touch and prolonged standing.'),H('alleviating','Relief','What helps?','Elevating the leg helps the ache.','Elevation relieves aching.'),H('treatment','Care so far','What have you put on it?','I washed it with soap and water and used plain petroleum jelly.','Cleansed with soap/water; petrolatum only.'),H('past_occurrence','Previous episode','Have you had this before?','No infection like this before.','No similar prior infection.')],
[X('pmh','Medical history','What health conditions do you have?','Varicose veins in both legs. No diabetes or immune condition.','Bilateral varicose veins; no known diabetes or immunocompromise.'),X('psh','Surgery and procedures','Have you had surgery or recent procedures?','No operations or recent procedures.','No surgical/procedural history.'),X('medications','Medication','What medicines do you take?','No regular medicine or steroid pills.','No regular medication or systemic steroids.'),X('allergies','Drug reactions','Are you allergic to medicines?','No known medicine allergies.','No known drug allergies.'),X('social','Smoking','Do you smoke?','I stopped smoking five years ago. Before that, half a pack daily for 12 years.','Former smoker: 6 pack-years; quit 5 years ago.'),X('social','Alcohol','How much alcohol do you drink?','I do not drink alcohol.','No alcohol.'),X('social','Drugs','Do you use recreational drugs or inject anything?','No recreational or injected drugs.','No recreational/injection drugs.'),X('social','Work','What does your work involve?','I am a barber, standing most of the day.','Barber; prolonged standing.'),X('social','Home and support','Who can help you at home?','My partner can help check the edge of the redness.','Partner can monitor skin changes.'),X('family','Family history','Does anyone in your family have blood clots?','My mother had a leg clot after hip surgery. No unprovoked family clots that I know of.','Mother: postoperative DVT; no known unprovoked familial thrombosis.'),X('pmh','Tetanus','When was your last tetanus shot?','Three years ago.','Reported tetanus immunization 3 years ago.')],
[R('rash','skin',True,'The red patch is only on the shin.','Localized shin erythema.'),R('skin_drainage','skin',False,'No pus has come out.','No drainage.'),R('pruritus','skin',True,'A little itch at first, but now it is mostly sore.','Initial mild itch; pain now predominant.'),R('fever','general',False,'No fever.','No fever.'),R('chills','general',False,'No chills.','No chills.'),R('fatigue','general',False,'I do not feel ill.','No malaise.'),R('chest_pain','cardiovascular',False,'No chest pain.','No chest pain.'),R('dyspnea','cardiovascular',False,'No trouble breathing.','No dyspnea.'),R('edema','cardiovascular',True,'Only a little puffiness right around the red spot, not the whole calf.','Localized swelling; no whole-calf swelling.')],
[E('general_inspect','Well appearing and hemodynamically stable.'),E('skin_inspect','Anterior left shin: 8 by 10 cm poorly demarcated erythema surrounding a superficial scratch, without vesicles, bullae, necrosis or purulent drainage. Visible superficial varicosities.',['legs']),E('msk_palpate','Skin warm and tender without fluctuance, crepitus, pain beyond visible margins or a palpable venous cord.',['point tenderness']),E('extremities','Mild localized edema at lesion; calves symmetric and nontender; capillary refill under 2 seconds.',['edema','calf symmetry','calf tenderness','capillary refill']),E('peripheral_pulses','Pedal pulses 2+ bilaterally.',['dorsalis pedis','posterior tibial']),E('heart_auscultate','Regular rate and rhythm without murmur.'),E('lungs_auscultate','Clear bilateral breath sounds.',['posterior','on skin','compare side to side','mouth open']),E('osteo_screen','L2 left lumbar paraspinal tissue texture change and tenderness.',['lumbar'],False)],
[D('Nonpurulent cellulitis','I',['hpi_location','hpi_chronology','exam_skin_inspect','exam_msk_palpate'],'Progressive warmth/tenderness around a skin break supports cellulitis without abscess or systemic illness.'),D('Large local inflammatory reaction to an insect bite','A',['hpi_setting','symptom_pruritus'],'Outdoor exposure and initial itching allow a bite reaction; progressive tenderness and a visible scratch favor cellulitis.'),D('Superficial thrombophlebitis','V',['history_medical_history','hpi_aggravating','exam_skin_inspect'],'Varicosities and focal painful erythema support consideration; absence of a cord and diffuse contact-area inflammation make it less likely.')],
['Mark the erythema margin and start an appropriate oral streptococcal-active antibiotic after clinician assessment; a 5-day course is reasonable if improving, adjusted to response/local guidance. Elevate, clean and protect the scratch; no routine culture or MRSA coverage without indication. Review in 48–72 hours. Rapid spread, disproportionate pain, fever or systemic illness needs urgent evaluation.','If reassessment supports a noninfectious bite reaction, emphasize cool compresses and appropriate antipruritic treatment rather than unnecessary antibiotics. Explain the difference between itch-predominant local inflammation and worsening infection; monitor the marked margin.','If cord-like tenderness, progression or DVT features appear, use venous ultrasound to define extent and assess deep involvement before selecting treatment. Discuss leg elevation and safe symptom relief; emergency evaluation is needed for new chest pain or breathlessness.'],
[('IDSA skin and soft tissue infection guideline','https://www.idsociety.org/practice-guideline/skin-and-soft-tissue-infections/'),('Cellulitis reassessment and alternatives','https://www.nice.org.uk/guidance/ng141/chapter/Recommendations')],
'Describe a localized skin lesion and separate infection from inflammatory and venous mimics.','Is the area spreading, is pain disproportionate, and is there pus or a venous cord?','I will examine the skin and circulation. If this is a skin infection, we can treat it and mark the edge to track it. Review is needed within two to three days, sooner for rapid spread, severe pain or fever.','Your partner can help monitor the marked edge, and we can discuss breaks from standing at work.')

# Reviewed case-specific refinements before serialization.
FAMILY_EXTRA={
'cardio-exertional-leg-pain':('Sibling','Do you have siblings and are they healthy?','My younger sister has high blood pressure.','Younger sister: hypertension.'),
'pulm-episodic-wheeze':('Father','What health problems does your father have?','My father has no major illness that I know of.','Father: no known major illness.'),
'pulm-chronic-productive-cough':('Other family','What about your mother and siblings?','My mother has high blood pressure. My brother has no major illness that I know of.','Mother: hypertension; brother: no known major illness.'),
'msk-shoulder-overuse':('Other family','What about your father and siblings?','My father has high blood pressure. My sister has no major illness.','Father: hypertension; sister: no known major illness.'),
'msk-knee-injury':('Other family','What about your father and siblings?','My father has high blood pressure. My brother has gout.','Father: hypertension; brother: gout.'),
'msk-hand-stiffness':('Sibling','Do you have siblings?','One brother, with no major illness that I know of.','Brother: no known major illness.'),
'heent-ear-pain':('Other family','What about your mother and siblings?','My mother has high blood pressure. My brother has no major illness.','Mother: hypertension; brother: no known major illness.'),
'heent-sore-throat':('Mother','What health problems does your mother have?','My mother has high blood pressure.','Mother: hypertension.'),
'skin-contact-rash':('Parents','What health problems do your parents have?','My mother has high blood pressure. My father has no major illness.','Mother: hypertension; father: no known major illness.'),
'skin-localized-redness':('Other family','What about your father and siblings?','My father has high blood pressure. My sister has no major illness.','Father: hypertension; sister: no known major illness.'),
}
for spec in CASES:
    spec['hist'].append(X('family',*FAMILY_EXTRA[spec['cid']]))
    if spec['cid']=='pulm-episodic-wheeze':
        old=spec['dx'][1];spec['dx'][1]=D('Irritant-triggered inducible laryngeal obstruction','I2',old[2],old[3],['inducible laryngeal obstruction','vocal cord dysfunction'])
        spec['plans'][0]=spec['plans'][0].replace('Reduce dust exposure without assuming she must quit work','Arrange temporary duties away from flour exposure pending occupational assessment')
    if spec['cid']=='msk-knee-injury':
        spec['ros']=[R(k,s,p,('The right knee hurts; no other joint hurts right now.' if k=='joint_pain' else a),n) for k,s,p,a,n in spec['ros']]
    if spec['cid']=='msk-shoulder-overuse':
        spec['hpi']=[(k,l,q,a,('No fall or sudden injury.' if k=='setting' else n)) for k,l,q,a,n in spec['hpi']]
# Only Plan1 holds the general appointment interval. Alternative actions are
# conditional; same-day/emergency escalation remains where clinical safety needs it.
import re
for spec in CASES:
    for i in (1,2):
        p=spec['plans'][i]
        p=re.sub(r'; (?:arrange follow-up|reassess|review[^;.]*) (?:within|in|after) [^;.]+[.]','.',p,flags=re.I)
        p=re.sub(r'; review the referral at the 2-week visit[.]','.',p)
        p=p.replace('; reassess with the shoulder in 3 weeks.','.').replace('; review results in 1–2 weeks alongside rheumatology referral.','.').replace('; reassess symptom response in 4 weeks.','.').replace('; reassess functional needs in 2–4 weeks.','.').replace('; review imaging within 2 weeks and seek earlier care for hemoptysis.','; seek earlier care for hemoptysis.')
        spec['plans'][i]=p

SOURCE_EXTRA={
'cardio-exertional-leg-pain':[('Lumbar spinal stenosis','https://orthoinfo.aaos.org/en/diseases--conditions/lumbar-spinal-stenosis/')],
'pulm-episodic-wheeze':[('Work-related asthma diagnosis and differentials','https://www.cdc.gov/niosh/asthma/hcp/diagnosing/index.html')],
'pulm-chronic-productive-cough':[('Bronchiectasis symptoms','https://www.nhlbi.nih.gov/health/bronchiectasis/symptoms')],
'msk-knee-injury':[('Gout diagnosis and treatment','https://www.niams.nih.gov/health-topics/gout/diagnosis-treatment-and-steps-to-take')],
'msk-hand-stiffness':[('NICE rheumatoid arthritis recommendations','https://www.nice.org.uk/guidance/ng100/chapter/Recommendations')],
'heent-ear-pain':[('Temporomandibular disorders','https://www.nidcr.nih.gov/health-info/tmd')],
'heent-sore-throat':[('Allergic rhinitis','https://www.entnet.org/resource/aao-hnsf-cpg-allergic-rhinitis-press-release-fact-sheet/')],
'skin-contact-rash':[('Ringworm diagnosis','https://www.cdc.gov/ringworm/hcp/clinical-overview/index.html')],
}
DEFAULT_VITALS={'BP':'122/76 mmHg','P':'76 bpm','R':'16 rpm','T':'98.3 F oral','Pulse Ox':'98% on room air','Ht':'5\' 7"','Wt':'156 lbs'}
# These are completed fictional measurements, not population-derived defaults.
INDIVIDUAL_VITALS={
'pulm-episodic-wheeze':{'BP':'116/72 mmHg','P':'84 bpm','R':'18 rpm','T':'98.2 F oral','Pulse Ox':'98% on room air','Ht':'5\' 4"','Wt':'138 lbs'},
'msk-shoulder-overuse':{'BP':'128/78 mmHg','P':'72 bpm','R':'16 rpm','T':'98.4 F oral','Pulse Ox':'99% on room air','Ht':'5\' 6"','Wt':'172 lbs'},
'msk-knee-injury':{'BP':'138/84 mmHg','P':'78 bpm','R':'16 rpm','T':'98.5 F oral','Pulse Ox':'98% on room air','Ht':'5\' 11"','Wt':'206 lbs'},
'msk-hand-stiffness':{'BP':'114/70 mmHg','P':'80 bpm','R':'16 rpm','T':'98.6 F oral','Pulse Ox':'99% on room air','Ht':'5\' 5"','Wt':'148 lbs'},
'heent-ear-pain':{'BP':'118/74 mmHg','P':'72 bpm','R':'14 rpm','T':'98.4 F oral','Pulse Ox':'99% on room air','Ht':'5\' 10"','Wt':'166 lbs'},
'heent-sore-throat':{'BP':'110/68 mmHg','P':'82 bpm','R':'16 rpm','T':'98.9 F oral','Pulse Ox':'99% on room air','Ht':'5\' 3"','Wt':'136 lbs'},
'skin-contact-rash':{'BP':'112/70 mmHg','P':'74 bpm','R':'14 rpm','T':'98.2 F oral','Pulse Ox':'99% on room air','Ht':'5\' 6"','Wt':'145 lbs'},
'skin-localized-redness':{'BP':'126/78 mmHg','P':'84 bpm','R':'16 rpm','T':'99.0 F oral','Pulse Ox':'98% on room air','Ht':'6\' 0"','Wt':'190 lbs'},
}
SYMPTOM_ALIASES={
'dyspnea':['short of breath','shortness of breath','breathless'],'hemoptysis':['coughing blood','blood in sputum'],
'myalgia':['muscle aches','body aches'],'pruritus':['itching','itchy'],'edema':['swelling','swollen ankles'],
'rhinorrhea':['runny nose'],'joint_swelling':['swollen joints'],'skin_drainage':['pus','drainage'],'ear_discharge':['ear drainage'],
'hearing_loss':['hearing','muffled'],'weakness':['weak','weakness'],'chest_pain':['chest pain','chest pressure'],
'orthopnea':['lie flat','lying flat'],'night_sweats':['night sweats'],'sore_throat':['sore throat'],
'numbness':['numbness','numb'],'tingling':['pins and needles','tingling'],'wheezing':['wheezing','wheeze'],'weight_loss':['weight loss'],
}
HPI_ALIASES={'onset':['when did','started','began'],'location':['where','which side'],'radiation':['spread','radiate'],
'quality':['feel like','describe'],'severity':['how bad','out of ten','severity'],'timing':['how long each','how often'],
'chronology':['changed','progressed'],'setting':['trigger','doing when'],'aggravating':['makes worse'],'alleviating':['helps','relieves'],
'past_occurrence':['had before'],'treatment':['tried for','taken for']}

def slug(s):return re.sub('[^a-z0-9]+','_',s.lower()).strip('_')
def make_fact(fid,category,label,q,answer,prose,ros=None,positive=True):
    concepts={fid:{'polarity':'positive' if positive else 'negative','value':answer}}
    f={'id':fid,'category':category,'print_label':label,'checklist':'h_'+fid,'value':answer,'sp_says':[answer],
       'triggers':{'any':[q]},'concepts':concepts,'example_questions':[q],
       'delivery_contract':{'versions':[{'text':answer,'concepts':copy.deepcopy(concepts),'complete_fact':True}],
                            'review_status':'author_statement_contract_checked_not_clinician_approved'},
       'authored_note':prose}
    if ros:f['ros_system']=ros
    if category=='onset':f['temporal_role']='first_episode_onset'
    if category=='chronology':f['question_dimensions']=['progression'];f['temporal_role']='pattern_or_progression'
    if category=='timing':
        dimensions=[]
        if re.search(r'how long|last|duration',q,re.I):dimensions.append('episode_duration')
        if re.search(r'often|constant|every day|intermittent',q,re.I):dimensions.append('frequency')
        if dimensions:f['question_dimensions']=dimensions
        if 'episode_duration' in dimensions:f['temporal_role']='episode_duration'
    if category=='social':
        f['history_topic']={'Smoking':'tobacco','Alcohol':'alcohol','Drugs':'drugs','Work':'occupation'}.get(label,'social_context')
    return f

def build_case(s,index):
    cid=s['cid'];facts=[make_fact('opening_complaint','chief_complaint','Opening complaint','What brings you in today?',s['opening'],s['opening'])]
    for key,label,q,a,n in s['hpi']:facts.append(make_fact('hpi_'+key,key,label,q,a,n))
    for kind,label,q,a,n in s['hist']+s['extra']:
        fid='patient_concern' if kind=='concern' else 'history_'+slug(label)
        facts.append(make_fact(fid,kind,label,q,a,n))
    for key,rs,pos,a,n in s['ros']:
        q={'fever':'Have you had a fever?','cough':'Have you had a cough?','joint_pain':'Any other joint pain?','weakness':'Have you noticed weakness?','sore_throat':'Have you had a sore throat?'}.get(key,'Have you had '+key.replace('_',' ')+'?')
        facts.append(make_fact('symptom_'+key,'associated' if pos else 'pertinent_negative',key.replace('_',' ').capitalize(),q,a,n,rs,pos))
    if not any(f['category']=='concern' for f in facts):facts.append(make_fact('patient_concern','concern','Concern','What worries you most?','I want to know what is causing this and how to get back to my usual activities.','Wants explanation and return to usual activities.'))
    assert len({f['id'] for f in facts})==len(facts),cid
    # Authored clinical paraphrases use the existing lexicon; the audit still
    # requires the fact to be delivered and checks polarity, quantities and scope.
    lex={f['id']:list(dict.fromkeys([f['value'],f['authored_note']])) for f in facts}
    for f in facts:
        if f['id'].startswith('symptom_'):
            key=f['id'][8:];f['triggers']['any']+=SYMPTOM_ALIASES.get(key,[key.replace('_',' ')])
            lex[f['id']]+=SYMPTOM_ALIASES.get(key,[key.replace('_',' ')])
        if f['category'] in HPI_ALIASES:f['triggers']['any']+=HPI_ALIASES[f['category']]
    for category,questions in {'pmh':['What illnesses have you had?','Any medical conditions?'],'psh':['Have you had any operations?'],'medications':['What medications are you taking?'],'allergies':['Any medication allergies?']}.items():
        first=next((f for f in facts if f['category']==category),None)
        if first:first['example_questions']+=questions;first['triggers']['any']+=questions
    # The knee's planted-foot twist is explicitly the activity at injury onset.
    # The other new setting rows describe earlier exposures or general triggers,
    # which must not masquerade as what happened at the first symptom moment.
    if cid=='msk-knee-injury':
        next(f for f in facts if f['id']=='hpi_setting')['onset_activity']=True
    if cid=='pulm-episodic-wheeze':lex['hpi_location']+=['chest tightness','tight chest']
    if cid=='heent-sore-throat':lex['opening_complaint']+=['sore throat'];lex['hpi_severity']+=['odynophagia']
    exammap={};physical=[];optional={}
    for mid,text,components,core in s['exams']:
        if s['system']=='Skin' and mid=='msk_palpate':mid='skin_palpate';components=['tenderness','warmth','induration','fluctuance']
        man=physexam.CATALOG_BY_ID[mid];components=components if components is not None else man['components']
        assert set(components)<=set(man['components']),(cid,mid)
        fid='exam_'+mid;concepts={fid:{'polarity':'positive','value':text}}
        exammap[mid]=[{'id':fid,'text':text,'concepts':concepts,'scopes':man.get('scope',[]),'checklist':'p_'+fid,'requires_components':components,'key_finding':core}]
        physical.append({'id':'p_'+fid,'text':man['label'],'maneuver':mid,'components':components})
        lex[fid]=[text]
        if not core:optional[mid]='Include when practicing the course structural screen; it does not establish the cause of the complaint.'
    for key,label in [('introduce','Introduce yourself and verify identity'),('hand_hygiene','Clean hands before examination'),('drape','Provide appropriate draping')]:physical.append({'id':'p_'+key,'text':label,'courtesy':key})
    # Source notes are assembled only from authored excerpts; the lesson builder
    # independently replaces Objective with findings actually released by actions.
    hpi=' '.join(f['authored_note'] for f in facts if f['id'].startswith('hpi_'))
    subj=f'CC: {s["opening"]}\n\nHPI: {s["age"]}-year-old {s["sex"]}. {hpi}'
    for tag,cats in [('PMH',{'pmh'}),('PSH',{'psh'}),('Meds',{'medications'}),('SH',{'social','obgyn'}),('FH',{'family'}),('Allergies',{'allergies'})]:
        subj+='\n\n'+tag+': '+' '.join(f['authored_note'] for f in facts if f['category'] in cats)
    ros=[]
    for rs in dict.fromkeys(r[1] for r in s['ros']):ros.append(rs.capitalize()+': '+' '.join(f['authored_note'] for f in facts if f.get('ros_system')==rs))
    subj+='\n\nROS: '+' '.join(ros)
    extras=[f['authored_note'] for f in facts if not f.get('ros_system') and f['category']=='pertinent_negative']
    if extras:subj+=' '+' '.join(extras)
    diffs=[]
    ids={f['id'] for f in facts}|set(lex)
    for rank,(name,cat,support,reason,aliases) in enumerate(s['dx'],1):
        support=[x.replace('exam_msk_palpate','exam_skin_palpate') if s['system']=='Skin' else x for x in support]
        assert set(support)<=ids,(cid,name,set(support)-ids)
        diffs.append({'rank':rank,'name':name,'vindicate':cat,'aliases':aliases,'supported_by':support,'teaching_context':reason})
    vitals=s['vitals'] or INDIVIDUAL_VITALS.get(cid,DEFAULT_VITALS)
    objective_groups={}
    for mid,rows in exammap.items():
        region='Lymphatic' if s['system']=='Skin' and mid=='lymph_nodes' else physexam.CATALOG_BY_ID[mid]['region']
        objective_groups.setdefault(region,[]).append(rows[0]['text'])
    aoc_regions={'Cardiovascular':{'Heart','Skin','Musculoskeletal','Neurologic'},'Respiratory':{'Lungs'},'Musculoskeletal':{'Musculoskeletal'},'HEENT':{'HEENT'},'Skin':{'Skin'}}[s['system']]
    aoc_methods=list(dict.fromkeys(physexam.CATALOG_BY_ID[m]['method'] for m in exammap if physexam.CATALOG_BY_ID[m]['region'] in aoc_regions and physexam.CATALOG_BY_ID[m]['method'] in ('inspect','palpate','percuss','auscultate')))
    notes={'S':subj,'O':'Vitals: '+', '.join(k+' '+v for k,v in vitals.items())+'\n\n'+'\n'.join(region+': '+' '.join(texts) for region,texts in objective_groups.items()),'A':[str(d['rank'])+'. '+d['name'] for d in diffs],'P':[str(i)+'. '+p for i,p in enumerate(s['plans'],1)]}
    firstconcern=next(f for f in facts if f['category']=='concern')
    appearance={'presentation':s['sex'],'model':'mpfb-public-patient','skinTone':1,'eyeColor':'brown','hairColor':'brunette','hairStyle':'bald' if s['sex']=='male' else 'long','outfit':'fitted-casual','bodyBuild':'standard'}
    c={'id':cid,'presentation_id':cid,'title':s['title'],'hidden_label':'Station '+str(25+index),'system':s['system'],'complaint_family':s['system'],'level':'M2','difficulty':'intermediate','blurb':s['opening'],
       'curriculum_note':'Supplementary fictional practice for the course history, physical examination and SOAP skills; not an official or predicted station.','scope_status':'supplementary_cross_system',
       'station':{'doorway':[f'{s["name"]}, {s["age"]}-year-old {s["sex"]}.',s['opening'],'Vital signs are available on the chart.','Perform a focused history and physical examination, discuss your plan, and document only what you obtain.','Use the time limit stated for your selected practice mode.'],'vitals':vitals,'supplied_results':[]},
       'patient':{'name':s['name'],'age':s['age'],'sex':s['sex'],'pronouns':'he/him' if s['sex']=='male' else 'she/her','persona':' '.join(f['value'] for f in facts if f['category']=='social' and f.get('print_label') in ('Work','Home','Support')),'opening':s['opening'],'opening_facts':['opening_complaint'],'opening_contract':{'text':s['opening'],'fact_ids':['opening_complaint'],'review':'Exact opening only.'},'volunteer_budget':1,'volunteer_order':['patient_concern'],'affect':firstconcern['value'],'communication_style':'concise','empathy_replies':['Thank you for listening.','I appreciate you explaining that.'],'closing_questions':[firstconcern['value']],'appearance':appearance,'voice':{'rate':1,'pitch':1,'gender':s['sex'],'adult':True},'education_responses':[{'student':s['closing'],'patient':'Thank you. I understand that the next steps depend on the examination and tests.'},{'student':s['concern'],'patient':'That would help. Thank you.'}]},
       'facts':facts,'concept_lexicon':lex,'exam_findings':exammap,'refusals':[],'refusal_expectation':{},
       'area_of_concern':{'system':s['system'],'required_methods':aoc_methods,'special_tests':[],'note':s['goal']},
       'osteopathic':{'expected_documentation':'Document the supplied level and palpatory descriptor only after the structural screen; treatment is not implied.'},'ros_pertinent_systems':list(dict.fromkeys(r[1] for r in s['ros'])),
       'differentials':diffs,'implausible_differentials':[],'plan_expectations':{'tests':[],'medications':[],'omt':[],'education':[],'referral':[],'follow_up':[]},
       'checklist':{'history':[{'id':f['checklist'],'text':f['print_label']} for f in facts],'physical':physical},'model_note':notes,
       'print_additional_exams':optional,'ideal_encounter_extras':[s['goal']],'supersedes_core':[],
       'review_status':'Source-checked fictional practice; not faculty or clinician approved.',
       'clinical_review':{'status':'source_checked_not_clinician_approved','date':DATE,'method':'Individual presentation, differential, safety and plan review against named primary clinical references plus course documentation constraints.','limits':'Fictional details deliberately authored. Mnemonic category placement is instructional and is not proof of etiology. Generic 3D appearance is not a diagnostic visual.','sources':[u for _,u in s['source']+SOURCE_EXTRA.get(cid,[])]},
       'sources':[{'title':'2026 FALL M2 ILG Student Manual','path':'claude builds/PCM/2026 FALL M2 ILG - STUDENT MANUAL update.docx','locator':'SOAP rubric and physical examination requirements','kind':'course'}]+[{'title':t,'url':u,'kind':'supplementary_clinical','reviewed':DATE,'review_scope':'Presentation pattern, relevant alternatives, diagnostic direction and safe initial management. Fictional history/vitals/findings are authored, not extracted patient data.'} for t,u in s['source']+SOURCE_EXTRA.get(cid,[])],
       'teaching':{'goals':[s['goal'],'Document only supplied, asked or examined information.'],'skills':['history-sequencing','focused-examination','clinical-reasoning','evidence-based-soap',slug(s['system'])],'common_omissions':['Distinguishing history from examination evidence.','Explaining uncertainty and the practical follow-up plan.'],
                   'lesson_plan':{'notice':s['goal'],'anchor':s['title'],'pivot':s['decision'],'exam':'Use the supported case-specific maneuvers and document their actual findings; do not infer normal findings from the generic model.','avoid':'Treating an unperformed examination or a possible diagnosis as obtained fact.'},'closing_dialogue':[s['closing']],'concern_response':s['concern'],
                   'reasoning_steps':[{'id':'orient','phase':'history','purpose':'Hear the presenting concern','question':'What brings you in today?','fact_ids':['opening_complaint'],'why':s['goal']},{'id':'pattern','phase':'history','purpose':'Clarify the pattern','question':s['decision'],'fact_ids':['hpi_onset'],'why':s['goal']},{'id':'examine','phase':'exam','purpose':'Perform relevant examinations','question':'May I examine you?','fact_ids':[],'why':'Findings require performed actions.'}],
                   'reasoning_map':[{'id':cid+'-decision','question':s['decision'],'why':s['goal'],'if_present':'Use the reported pattern to select the relevant examinations and assess urgency.','if_absent':'Keep alternatives open and ask a focused follow-up.','next_action':'Perform the relevant case-specific examination.','document':'Separate reported symptoms, observed signs, assessment and proposed care.'}],
                   'classification_note':'Categories reflect the explicitly proposed mechanism; e.g., irritant exposure is I2. They are a course organizing aid, not confirmation of mechanism.'},
       'content_revisions':{'library_expansion_20260914':'New independently authored presentation. Single core path; no renamed cosmetic variants.'}}
    if s['system']=='Skin':c['print_exam_systems']={'skin_palpate':'Skin','lymph_nodes':'Lymphatic'}
    if s['system'] in ('Skin','HEENT'):
        c['examination_display_note']='The case-specific skin, ear, nose and throat appearance is supplied in the labeled examination result; the generic patient model does not reliably display these findings.'
    # Suppress only generic history topics that this case authors; no invented
    # normal ROS is borrowed from defaults. Unspecified information stays unknown.
    c['supersedes_core']=list(dict.fromkeys((['chest_pain'] if cid=='pulm-episodic-wheeze' else ['sore_throat'] if cid=='heent-sore-throat' else [])+['tobacco_use','alcohol_use','drug_use','allergies','medications','family_history','past_medical','past_surgical']+[r[0] for r in s['ros']]))
    return c

def main():
    import argparse
    parser=argparse.ArgumentParser();parser.add_argument('--output',type=Path,default=ROOT/'pcmcse/cases');args=parser.parse_args()
    args.output.mkdir(parents=True,exist_ok=True)
    built=[]
    for i,s in enumerate(CASES):
        c=build_case(s,i);(args.output/(c['id'].replace('-','_')+'.json')).write_text(json.dumps(c,indent=2,ensure_ascii=False)+'\n')
        built.append({'id':c['id'],'facts':len(c['facts']),'exams':len(c['exam_findings']),'note_words':len(' '.join([c['model_note']['S'],c['model_note']['O']]+c['model_note']['A']+c['model_note']['P']).split())})
    print(json.dumps(built,indent=2))
if __name__=='__main__':main()
