const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fs=require('fs'),assert=require('assert/strict'),crypto=require('crypto');
const out=process.env.CSE_TEST_OUTPUT||require('path').join(require('os').tmpdir(),'cse-animation-review'),root=require('path').resolve(__dirname,'..'),base=(process.env.CSE_TEST_URL||'http://127.0.0.1:8776/web/');
fs.mkdirSync(out,{recursive:true});
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true});try{
const c=await b.newContext({viewport:{width:1440,height:900},recordVideo:{dir:out+'/lifecycle-video',size:{width:1440,height:900}}}),p=await c.newPage(),errors=[],checks=[];p.on('pageerror',e=>errors.push(e.message));
await p.goto(base+'#practice');await p.locator('#btnStart').waitFor({timeout:120000});await p.locator('[data-mode=rehearsal]').click();await p.locator('[data-case="cardio-febrile-cough"]').click();await p.locator('#btnStart').click();await p.locator('#skipEntrance').click();await p.locator('#say').waitFor();
await p.locator('#say').fill('Please keep this question while I examine you.');await p.locator('[data-ew-tab=exam]').click();if(await p.locator('#ewExamAll').isVisible())await p.locator('#ewExamAll').click();
async function begin(key,q){await p.locator('#manSearch').fill(q);await p.locator('[data-exam-action="'+key+'"]').click();await p.locator('.exam-demo').waitFor();return p.evaluate(()=>structuredClone(S.pending_exam));}
const completed=()=>p.evaluate(()=>S.examination_activity.filter(e=>e.kind==='exam_action'&&e.meta.status==='completed').length);
let n=await completed(),pending=await begin('jvd:complete','jugular'),end=await p.evaluate(()=>S.phase_ends_at);let stages=new Set(),frames=new Set();
while(await p.locator('.exam-demo').count()){const sample=await p.locator('.exam-demo').evaluate(el=>({i:el.dataset.stage,svg:el.querySelector('svg')?.outerHTML})).catch(()=>null);if(sample){stages.add(sample.i);frames.add(sample.svg);}await p.waitForTimeout(180);}
assert.equal(await completed(),n+1);assert.equal(await p.evaluate(()=>S.phase_ends_at),end);assert.equal(stages.size,3);checks.push('Real-time JVD playback completed all 3 stages and released one completion, with no additional clock deduction.');
await p.getByRole('button',{name:'Replay technique',exact:true}).click();await p.waitForTimeout(800);assert.equal(await completed(),n+1);assert.equal(await p.evaluate(()=>S.phase_ends_at),end);await p.getByRole('button',{name:'Exit replay'}).click();checks.push('Teaching replay did not call the examination engine, add evidence or alter the deadline.');
pending=await begin('jvd:complete','jugular');await p.waitForTimeout(5000);assert.equal(await completed(),n+1);end=await p.evaluate(()=>S.phase_ends_at);await p.locator('.exam-demo-skip').dblclick();await p.waitForFunction(()=>!S.pending_exam);const charged=end-await p.evaluate(()=>S.phase_ends_at);assert(charged>8000&&charged<10500,charged);assert.equal(await completed(),n+2);checks.push('After approximately 5 seconds, repeated Skip clicks charged only the remaining '+charged+' ms and completed once.');
pending=await begin('jvd:complete','jugular');await p.waitForTimeout(900);n=await completed();end=await p.evaluate(()=>S.phase_ends_at);await p.locator('.exam-demo-cancel').click();await p.waitForFunction(()=>!S.pending_exam);assert.equal(await completed(),n);assert.equal(await p.evaluate(()=>S.phase_ends_at),end);checks.push('Cancel released no finding and imposed no extra time charge.');
pending=await begin('jvd:complete','jugular');await p.evaluate(()=>{const original=window.fetch;let failed=false;window.fetch=async(...args)=>{if(!failed&&String(args[0]).includes('/exam_control')){failed=true;throw new Error('Injected control failure');}return original(...args);};});await p.locator('.exam-demo-skip').click();await p.locator('.exam-demo-error').waitFor({state:'visible'});assert.equal(await completed(),n);assert.equal(await p.evaluate(()=>S.pending_exam.id),pending.id);await p.screenshot({path:out+'/final-control-error.png'});await p.locator('.exam-demo-skip').click();await p.waitForFunction(()=>!S.pending_exam);assert.equal(await completed(),n+1);checks.push('Injected control failure retained the running action, reported failure and allowed a successful single retry.');
await p.locator('[data-ew-tab=talk]').click();assert.equal(await p.locator('#say').inputValue(),'Please keep this question while I examine you.');await p.locator('[data-ew-tab=exam]').click();checks.push('Talk draft survived examining, replay, cancellation and retry.');
pending=await begin('orthostatic_vitals:complete','orthostatic');await p.reload();await p.locator('.exam-demo').waitFor({timeout:120000});assert.equal(await p.evaluate(()=>S.pending_exam.id),pending.id);assert.equal(await p.evaluate(()=>S.pending_exam.due_at),pending.due_at);checks.push('Refreshing during a pending examination resumed the same action and original due time.');
await p.locator('.exam-demo-cancel').click();await p.waitForFunction(()=>!S.pending_exam);
for(const [w,h] of [[1440,900],[1280,800],[1024,768],[768,1024],[640,500]]){await p.setViewportSize({width:w,height:h});pending=await begin('msk_slr:seated','seated straight');await p.waitForTimeout(1900);await p.locator('.exam-demo-skip').scrollIntoViewIfNeeded();const overflow=await p.evaluate(()=>document.documentElement.scrollWidth>innerWidth+1);assert.equal(overflow,false,w+' overflow');const box=await p.locator('.exam-demo-skip').boundingBox();assert(box.x>=0&&box.x+box.width<=w+1&&box.height>=40);await p.screenshot({path:out+`/final-exam-${w}x${h}.png`});await p.locator('.exam-demo-cancel').click();await p.waitForFunction(()=>!S.pending_exam);}
checks.push('Controls remained reachable without page-width overflow at desktop, tablet portrait/landscape and 640px reflow widths.');
await p.setViewportSize({width:1440,height:900});
await p.emulateMedia({reducedMotion:'reduce'});await begin('jvd:complete','jugular');
const still=await p.locator('.exam-demo-canvas').innerHTML(),clockBefore=await p.locator('progress[aria-label="Examination animation progress"]').getAttribute('value');
await p.waitForTimeout(700);assert.equal(await p.locator('.exam-demo-canvas').innerHTML(),still);assert(Number(await p.locator('progress[aria-label="Examination animation progress"]').getAttribute('value'))>Number(clockBefore));
await p.locator('.exam-demo-cancel').focus();await p.keyboard.press('Enter');await p.waitForFunction(()=>!S.pending_exam);await p.waitForFunction(()=>document.activeElement?.id==='manSearch');await p.emulateMedia({reducedMotion:'no-preference'});
checks.push('Reduced motion retained stage timing without moving artwork; keyboard cancellation restored focus to examination search.');
// Use the actual visible full-length action to consume the disposable timer.
// This reaches the deadline through user behavior, without changing saved data.
n=await completed();await begin('orthostatic_vitals:complete','orthostatic');await p.locator('.exam-demo-skip').click();await p.waitForFunction(()=>!S.pending_exam);assert.equal(await completed(),n+1);
await begin('orthostatic_vitals:complete','orthostatic');await p.locator('.exam-demo-skip').click();await p.locator('#noteS').waitFor();assert.equal(await p.evaluate(()=>S.phase),'note');assert.equal(await completed(),n+1);assert.equal(await p.locator('.exam-demo').count(),0);checks.push('Skipping an exam that could not finish before the deadline opened the note workspace and released no late finding.');
const assets=[];for(const file of ['index.html','exam-animation.js','exam-animation.css','encounter-workspace.js','engine.zip']){const res=await c.request.get(base+file);assert(res.ok());const bytes=await res.body(),hash=crypto.createHash('sha256').update(bytes).digest('hex');assert.equal(hash,crypto.createHash('sha256').update(fs.readFileSync(root+'/web/'+file)).digest('hex'));assets.push({file,sha256:hash});}
assert.deepEqual(errors,[]);fs.writeFileSync(out+'/lifecycle-browser-results.json',JSON.stringify({checks,stages:[...stages],frames:frames.size,errors,assets},null,2));console.log(JSON.stringify({checks,errors},null,2));await c.close();
}finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
