/** Inject an actual GPU context interruption in a disposable timed encounter.
 * BFCache PageTransitionEvent check exercises our listener only; it is not a
 * claim that automation can reproduce every Safari process-cache eviction. */
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fs=require('fs'),path=require('path'),assert=require('node:assert/strict'),crypto=require('crypto');
const root=path.resolve(__dirname,'..'),out=process.env.CSE_TEST_OUTPUT||path.join(require('os').tmpdir(),'cse-context-recovery');fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});const context=await browser.newContext({viewport:{width:1180,height:820}});await context.addInitScript(()=>{window.roomEvents=[];window.addEventListener('message',e=>{if(e.origin===location.origin&&String(e.data?.type).startsWith('pcm-'))roomEvents.push(e.data);});});const p=await context.newPage();await p.goto(process.env.CSE_TEST_URL||'http://127.0.0.1:8776/web/');await p.locator('[data-portal-go=practice]').first().click({timeout:120000});await p.locator('#btnStart').waitFor();await p.evaluate(()=>begin(false,{case_id:'msk-hand-stiffness',variant_id:'base',learning_mode:'independent',mode:'text'}));await p.locator('#skipEntrance').click();await p.locator('#say').waitFor({timeout:120000});const f=p.frames().find(f=>f.url().includes('patient3d/index.html'));await p.waitForFunction(()=>patientDisplayStates.get(S.id)==='ready',{},{timeout:60000});await p.locator('#say').fill('Tell me more about the stiffness.');const before=await p.evaluate(()=>({id:S.id,deadline:S.phase_ends_at,phase:S.phase,events:S.event_seq,draft:document.querySelector('#say').value}));assert(before.deadline>Date.now());
 const extension=await f.evaluate(()=>{const canvas=document.querySelector('canvas'),gl=canvas.getContext('webgl2')||canvas.getContext('webgl');window.contextRecoveryExtension=gl.getExtension('WEBGL_lose_context');return !!contextRecoveryExtension;});assert(extension,'WEBGL_lose_context required for this regression');await f.evaluate(()=>contextRecoveryExtension.loseContext());await p.waitForFunction(()=>roomEvents.some(e=>e.type==='pcm-unity-error'));
 assert.equal(await p.evaluate(()=>roomEvents.some(e=>e.type==='pcm-room-restored')),false,'Do not claim restoration while context is lost');await f.evaluate(()=>contextRecoveryExtension.restoreContext());await p.waitForFunction(()=>roomEvents.some(e=>e.type==='pcm-room-restored'&&e.reason==='graphics-context'),{},{timeout:60000});
 const geometry=await f.evaluate(()=>({ready:pcmRoomInspection().scene.isReady(),bodies:pcmRoomInspection().scene.getActiveMeshes().data.filter(m=>m&&m.name==='PCM_PublicBody'&&m.isEnabled()&&m.isReady(true)).map(m=>m.getTotalVertices())}));assert.equal(geometry.ready,true);assert.deepEqual(geometry.bodies,[9247]);assert.match(await p.locator('#unityStatus').innerText(),/Patient ready/);assert.equal(await p.locator('#say').inputValue(),before.draft);const after=await p.evaluate(()=>({id:S.id,deadline:S.phase_ends_at,phase:S.phase,events:S.event_seq}));assert.deepEqual(after,{id:before.id,deadline:before.deadline,phase:before.phase,events:before.events});
 await f.evaluate(()=>{window.dispatchEvent(new PageTransitionEvent('pagehide',{persisted:true}));window.dispatchEvent(new PageTransitionEvent('pageshow',{persisted:true}));});await p.waitForFunction(()=>roomEvents.some(e=>e.type==='pcm-room-restored'&&e.reason==='page-cache'),{},{timeout:30000});assert.equal(await f.evaluate(()=>pcmRoomInspection().scene.getEngine().isDisposed),false);assert.equal(await p.locator('#say').inputValue(),before.draft);assert.equal(await p.evaluate(()=>S.phase_ends_at),before.deadline);await p.screenshot({path:path.join(out,'recovered-encounter.png')});
 const report={before,after,geometry,events:await p.evaluate(()=>roomEvents.filter(e=>['pcm-room-restored','pcm-unity-error'].includes(e.type))),hashes:Object.fromEntries(['web/app.js','web/patient3d/src/room.js','web/patient3d/dist/room.js'].map(file=>[file,crypto.createHash('sha256').update(fs.readFileSync(path.join(root,file))).digest('hex')])),limits:'GPU interruption used WEBGL_lose_context; BFCache preservation tested our persisted PageTransitionEvent handler, not physical-device process eviction.'};fs.writeFileSync(path.join(out,'context-recovery.json'),JSON.stringify(report,null,2));console.log('PASS actualGPU loss→restoredframe andappstatus; preserved draft, attempt, deadline, phase, eventsequence; persistedpage listener keepsenginealive.');await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
