const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('assert/strict'),fs=require('fs');
const base=process.env.CSE_TEST_URL||'http://127.0.0.1:8775/web/',out=process.env.CSE_TEST_OUTPUT||require('os').tmpdir()+'/cse-print-browser';fs.mkdirSync(out,{recursive:true});
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true}),c=await b.newContext({viewport:{width:1440,height:900}}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));
await p.goto(base+'#learn/cardio-febrile-cough');await p.locator('#printLesson').waitFor({timeout:120000});await p.waitForFunction(()=>!document.querySelector('#view').classList.contains('solution-locked')&&[...document.querySelectorAll('link[rel=stylesheet]')].every(n=>n.sheet));
async function choose(edition='patient'){await p.locator('#printLesson').click();await p.locator('#printDocumentChoice').waitFor();await p.locator(`[name=edition][value=${edition}]`).check();await p.locator('#preparePrintDocument').click();}
await p.locator('#recall-0').fill('Disposable reflection must survive printing.');
const original=await p.title();await p.locator('#printLesson').scrollIntoViewIfNeeded();await p.evaluate(()=>scrollTo(0,20));const before=await p.evaluate(()=>({x:scrollX,y:scrollY}));assert.equal(before.y,20);
await choose();await p.waitForFunction(()=>document.body.hasAttribute('data-walkthrough-preview'));assert.match(await p.title(),/Noah Rivera/);await p.screenshot({path:out+'/after-preview.png'});
assert.equal(await p.evaluate(()=>pcmPrintReport.edition),'patient');assert.equal(await p.locator('.rp-note-assessment').count(),0);
const hash=await p.evaluate(()=>location.hash);const hpiLink=p.locator('.rp-index [data-page-ref=history]');await hpiLink.click();assert.equal(await p.evaluate(()=>location.hash),hash);assert.match(await hpiLink.innerText(),/p\. \d+/);assert(await p.locator('#rp-history').isVisible());

await p.locator('#pwClosePrint').click();assert.equal(await p.title(),original);assert.equal(await p.evaluate(()=>document.activeElement.id),'printLesson');assert.deepEqual(await p.evaluate(()=>({x:scrollX,y:scrollY})),before);assert.equal(await p.locator('#recall-0').inputValue(),'Disposable reflection must survive printing.');
await p.locator('#printLesson').click();assert.equal(await p.locator('[name=edition][value=patient]').isChecked(),true);await p.screenshot({path:out+'/document-choice.png'});await p.keyboard.press('Escape');await p.locator('#printDocumentChoice').waitFor({state:'detached',timeout:3000});assert.equal(await p.locator('#printDocumentChoice').count(),0);assert.deepEqual(await p.evaluate(()=>({x:scrollX,y:scrollY})),before);
for(const edition of ['soap','examiner']){await choose(edition);await p.waitForFunction(()=>document.body.hasAttribute('data-walkthrough-preview'));const report=await p.evaluate(()=>pcmPrintReport);assert.equal(report.edition,edition);if(edition==='soap'){assert(await p.locator('.rp-note-assessment').count()>0);assert.equal(await p.locator('.rp-topic').count(),0);}else{assert.equal(await p.locator('.rp-note-assessment').count(),0);assert(await p.locator('.rp-exam-topic').count()>0);}await p.pdf({path:out+'/'+edition+'-visible-workflow.pdf',preferCSSPageSize:true,printBackground:true});fs.writeFileSync(out+'/'+edition+'-report.json',JSON.stringify(report));if(await p.locator('#pwClosePrint').isVisible())await p.locator('#pwClosePrint').click();}

await choose();await p.waitForFunction(()=>document.body.hasAttribute('data-walkthrough-preview'));await p.keyboard.press('Escape');assert.equal(await p.title(),original);assert.equal(await p.evaluate(()=>document.activeElement.id),'printLesson');
await p.setViewportSize({width:390,height:844});await choose();await p.waitForFunction(()=>document.body.hasAttribute('data-walkthrough-preview'));for(const id of ['#pwNativePrint','#pwClosePrint']){const r=await p.locator(id).boundingBox();assert(r.x>=0&&r.x+r.width<=390&&r.y>=0&&r.y+r.height<=844,JSON.stringify(r));}await p.screenshot({path:out+'/after-mobile-toolbar.png'});
await p.evaluate(()=>{window.print=()=>{window.testPrint={title:document.title,approved:document.body.dataset.walkthroughPrint};window.dispatchEvent(new Event('beforeprint'));window.dispatchEvent(new Event('afterprint'));};});await p.locator('#pwNativePrint').click();await p.waitForFunction(()=>!!window.testPrint);const print=await p.evaluate(()=>testPrint);assert.match(print.title,/Noah Rivera/);assert.equal(print.approved,'approved');assert.equal(await p.title(),original);
await p.waitForFunction(()=>!document.querySelector('#view').classList.contains('solution-locked'));await p.route('**/print-assets/manifest.json*',r=>r.fulfill({status:503,body:'unavailable'}));await choose('study');await p.locator('#printLessonStatus').filter({hasText:'could not be prepared'}).waitFor();assert.equal(await p.locator('body[data-walkthrough-preview]').count(),0);assert.equal(await p.locator('#printLesson').isEnabled(),true);assert.match(await p.locator('.lesson-reader h1').innerText(),/Fever, cough/);await p.unroute('**/print-assets/manifest.json*');await choose('study');await p.waitForFunction(()=>document.body.hasAttribute('data-walkthrough-preview'));await p.locator('#pwClosePrint').click();
await p.evaluate(()=>{const original=window.fetch;window.delayedAccessChecks=0;window.fetch=async(...args)=>{if(String(args[0]).endsWith('/api/teaching/status')){window.delayedAccessChecks++;await new Promise(r=>setTimeout(r,2300));}return original(...args);};});await choose();await p.waitForFunction(()=>document.body.hasAttribute('data-walkthrough-preview'),{},{timeout:15000});assert(await p.evaluate(()=>delayedAccessChecks)>0);await p.locator('#pwClosePrint').click();
await choose();await p.waitForFunction(()=>document.body.hasAttribute('data-walkthrough-preview'),{},{timeout:15000});
await p.evaluate(()=>{const original=window.fetch;window.fetch=(url,...args)=>String(url).endsWith('/api/teaching/status')?Promise.reject(Error('Isolated access failure')):original(url,...args);});
await p.waitForFunction(()=>document.querySelector('#view').classList.contains('solution-locked')&&!document.body.hasAttribute('data-walkthrough-preview'),{},{timeout:10000});await p.emulateMedia({media:'print'});const locked=await p.evaluate(()=>({approved:document.body.getAttribute('data-walkthrough-print'),print:getComputedStyle(document.querySelector('#walkthroughPrint')).display,reader:getComputedStyle(document.querySelector('.lesson-reader')).display}));assert.deepEqual(locked,{approved:null,print:'none',reader:'none'});
assert.deepEqual(errors,[]);fs.writeFileSync(out+'/interaction.json',JSON.stringify({passed:['preview','case-specific document title','return focus and scroll','Escape','390px toolbar buttons reachable','visible Print button with simulated native dialog lifecycle','manifest failure preserves reader and retry succeeds','slow access check survives periodic background checks','access failure hides preview and reader in print media'],errors,print},null,2));console.log('PASS print preview, title, Return, Escape, narrow controls, Print lifecycle, failed asset load and retry');await b.close();})().catch(e=>{console.error(e);process.exit(1)});
