const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright'),fs=require('fs'),path=require('path'),assert=require('assert/strict');
const root=path.resolve(__dirname,'..'),out=process.env.CSE_TEST_OUTPUT||path.join(require('os').tmpdir(),'cse-animation-review'),plans=Object.values(JSON.parse(fs.readFileSync(root+'/pcmcse/exam_demonstrations.json'))).filter(p=>p.maneuver_id!=='vitals_review');
fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({channel:'chrome',headless:true});try{
 const page=await browser.newPage({viewport:{width:1500,height:900}});await page.goto((process.env.CSE_TEST_URL||'http://127.0.0.1:8776/web/')+'exam-animation.css');await page.setContent('<style>body{font:14px system-ui;background:#fafbf5;color:#153e31}main{display:grid;grid-template-columns:repeat(5,1fr);gap:15px}.tile{border:1px solid #aaa}.exam-demo-canvas{height:220px}p{margin:6px}</style><main></main>');await page.addStyleTag({path:root+'/web/exam-animation.css'});await page.addStyleTag({content:'.tile .exam-demo-canvas,.tile .exam-demo-canvas svg{min-height:200px;max-height:220px;height:220px}'});await page.addScriptTag({path:root+'/web/exam-animation.js'});
 await page.evaluate(plans=>{window.review=[];let t0=performance.now();for(const plan of plans){let start=0;plan.steps.forEach((stage,i)=>{const element=document.createElement('section');element.className='tile';element.innerHTML='<p>'+plan.key+' · '+(i+1)+'</p><div class="exam-demo-canvas"></div><p>'+stage.caption+'</p>';document.querySelector('main').append(element);window.review.push({key:plan.key,plan,stage,i,start,element,frames:new Set(),captures:[],last:-1,ended:false});start+=stage.seconds;});}
 // Every stage plays at its authored speed. The 300-second setup rest and
 // standing and memory-recall waits are static; their full timing is verified in engine tests.
 function animate(){const elapsed=(performance.now()-t0)/1000;for(const row of review){const limit=row.stage.seconds,local=Math.min(elapsed,limit-.001),f=PCMExamAnimation.frame(row.plan,row.start+local,'back');if(row.ended)continue;row.element.querySelector('.exam-demo-canvas').innerHTML=f.svg;row.frames.add(f.svg);if(Math.floor(elapsed*4)>row.last){row.last=Math.floor(elapsed*4);row.captures.push({t:local,svg:f.svg});}if(elapsed>=limit)row.ended=true;}if(elapsed<31)requestAnimationFrame(animate);else window.done=true;}animate();},plans);
 await page.waitForFunction(()=>window.done,{},{timeout:40000});const records=await page.evaluate(()=>review.map(r=>({key:r.key,stage:r.i,action:r.stage.action,motion:r.stage.motion||'',seconds:r.stage.seconds,ended:r.ended,variants:r.frames.size,frames:r.captures})));
 assert.equal(new Set(records.map(x=>x.key)).size,85);assert(records.every(r=>r.frames.every(f=>!/NaN|Infinity|undefined/.test(f.svg))));
 // Static is legitimate for resisted holds; collect rather than equate visual
 // change with clinical accuracy. This report is reviewed alongside the plan.
 fs.writeFileSync(out+'/realtime-motion.json',JSON.stringify(records));
 const summary=records.map(({frames,...r})=>r);fs.writeFileSync(out+'/realtime-motion-summary.json',JSON.stringify(summary,null,2));
 // Actual successive frames from moving playback: each action gets its own
 // review sheet, retaining timestamps, stage names and start/end positions.
 for(const plan of plans){const rows=records.filter(r=>r.key===plan.key);await page.evaluate(rows=>{document.querySelector('main').style.display='block';document.querySelector('main').innerHTML=rows.map(r=>{const frames=[r.frames[0],r.frames[Math.floor(r.frames.length/2)],r.frames.at(-1)];return '<section style="display:grid;grid-template-columns:210px repeat(3,1fr);gap:12px;border-bottom:1px solid #aaa"><p>'+r.key+' stage '+(r.stage+1)+'<br>'+r.action+' '+r.motion+'</p>'+frames.map(f=>'<div><div class="exam-demo-canvas">'+f.svg+'</div><p>'+f.t.toFixed(2)+'s</p></div>').join('')+'</section>';}).join('');},rows);await page.screenshot({path:out+'/motion-'+plan.key.replace(':','-')+'.png',fullPage:true});}
 console.log(JSON.stringify({actions:plans.length,stages:records.length,completedStages:records.filter(r=>r.ended).length,waitingStages:records.filter(r=>!r.ended).map(r=>r.key),invalidGeometry:0}));
}finally{await browser.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
