// Regression: delayed initial focus restoration must not redirect note input.
// Uses fresh disposable browser storage; never touches existing learner attempts.
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fs=require('node:fs'),assert=require('node:assert/strict'),path=require('node:path');
const out=process.env.CSE_TEST_OUTPUT||path.join(require('node:os').tmpdir(),'cse-note-entry-focus');
const base=process.env.CSE_TEST_URL||'http://127.0.0.1:8773/web/';
fs.mkdirSync(out,{recursive:true});
(async()=>{const browser=await chromium.launch({channel:process.env.CSE_BROWSER||'chrome',headless:true});for(let run=1;run<=5;run++){
const ctx=await browser.newContext({viewport:{width:820,height:1180},isMobile:true,hasTouch:true,deviceScaleFactor:1});const p=await ctx.newPage();await p.goto(base+'#practice');await p.locator('#btnStart').waitFor({timeout:120000});await p.locator('label').filter({has:p.locator('input[name=uimode][value=guided]')}).tap();await p.locator('.station-card[data-case="cardio-palpitations"]').tap();await p.locator('#btnStart').tap();await p.locator('#skipEntrance').waitFor();await p.locator('#skipEntrance').tap();await p.locator('#say').waitFor();await p.waitForFunction(()=>S.phase==='encounter');
// Passive event and setter tracing exposes whether a failure came from a
// rerender, a value overwrite, or focus moving before the browser inserts text.
await p.evaluate(()=>{window.entryTrace=[];for(const kind of ['focusin','focusout','input','selectionchange'])document.addEventListener(kind,e=>{if(e.target?.id?.startsWith('note')||document.activeElement?.id?.startsWith('note'))entryTrace.push({t:performance.now(),kind,id:e.target.id,active:document.activeElement.id,value:e.target.value});},true);const desc=Object.getOwnPropertyDescriptor(HTMLTextAreaElement.prototype,'value');Object.defineProperty(HTMLTextAreaElement.prototype,'value',{...desc,set(v){if(this.id.startsWith('note'))entryTrace.push({t:performance.now(),kind:'set',id:this.id,value:v,stack:new Error().stack});desc.set.call(this,v)}});new MutationObserver(()=>{if(document.querySelector('#noteS')){const x=document.querySelector('#noteS');if(window.noteNode!==x){entryTrace.push({t:performance.now(),kind:'note-render',values:[...document.querySelectorAll('[id^=note]')].filter(e=>e.tagName==='TEXTAREA').map(e=>[e.id,e.value])});window.noteNode=x;}}}).observe(document.querySelector('#view'),{childList:true,subtree:true});});
await p.locator('#btnEnd').tap();await p.locator('.confirm-dialog button[value=confirm]').tap();await p.locator('#noteS').waitFor();const fields={noteS:'HPI\nPatient describes palpitations.\nROS\nNot obtained.',noteO:'General\nNot examined.'};for(let i=0;i<3;i++){fields['noteA'+i]='Assessment '+(i+1)+'\nAdditional reasoning.';fields['noteP'+i]='Plan '+(i+1)+'\nAdditional action.';}
// Intentionally start entry as soon as the visible editor is available.
// A settling sleep would conceal the initial restoration race being tested.
for(const [id,value]of Object.entries(fields)){await p.locator('#'+id).fill(value);}
await p.waitForFunction(()=>noteSave.state==='saved');await p.locator('#noteS').scrollIntoViewIfNeeded();const state=await p.evaluate(()=>({values:Object.fromEntries([...document.querySelectorAll('textarea[id^=note]')].map(e=>[e.id,e.value])),trace:entryTrace,phase:S.phase,draft:draftValue('note',S.id),note:collectNote()}));fs.writeFileSync(out+'/entry-stress-'+run+'.json',JSON.stringify(state,null,2));try{assert.deepEqual(state.values,fields)}catch(e){await p.screenshot({path:out+'/entry-stress-'+run+'.png'});console.log('FAIL',run,JSON.stringify(state.values));throw e;}console.log('PASS rapid tablet note entry',run);await ctx.close();}await browser.close();})().catch(e=>{console.error(e);process.exit(1)});
