const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const fs=require('fs'),path=require('path'),assert=require('assert/strict'),crypto=require('crypto');
const root=require('path').resolve(__dirname,'..'),out=process.env.CSE_TEST_OUTPUT||require('path').join(require('os').tmpdir(),'cse-animation-review'),plans=Object.values(JSON.parse(fs.readFileSync(root+'/pcmcse/exam_demonstrations.json'))).filter(x=>x.maneuver_id!=='vitals_review');
fs.mkdirSync(out,{recursive:true});
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true});try{
 const c=await b.newContext({viewport:{width:1440,height:900}}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));
 await p.goto((process.env.CSE_TEST_URL||'http://127.0.0.1:8776/web/')+'#practice');await p.locator('#btnStart').waitFor({timeout:120000});await p.locator('[data-mode=coached]').click();await p.locator('[data-case="cardio-febrile-cough"]').click();await p.locator('#btnStart').click();await p.locator('#skipEntrance').click();await p.locator('#say').waitFor();
 await p.locator('#say').fill('Keep this unsent question while examining.');await p.locator('[data-ew-tab=exam]').click();await p.locator('#ewExamAll').click();
 const logs=[];
 for(const plan of plans){console.log('Exam',plan.key);await p.locator('#manSearch').fill('');const action=p.locator('[data-exam-action="'+plan.key+'"]');if(!await action.isVisible())await p.locator('.ew-more-systems > summary').click();await action.scrollIntoViewIfNeeded();await action.waitFor({state:'visible'});assert.match(await action.textContent(),new RegExp('~'+plan.duration_s+'s'));await action.click();await p.locator('.exam-demo').waitFor();const duration=await p.evaluate(()=>S.pending_exam.duration_s);assert.equal(duration,plan.duration_s);
 assert.equal(await p.locator('[data-exam-action]:enabled').count(),0);
 await p.waitForTimeout(220);try{const skip=p.locator('.exam-demo-skip'),box=await skip.boundingBox();assert(box&&box.x>=0&&box.y>=0&&box.x+box.width<=1440&&box.y+box.height<=900);const x=box.x+box.width/2,y=box.y+box.height/2;assert(await p.evaluate(({x,y})=>!!document.elementFromPoint(x,y)?.closest('.exam-demo-skip'),{x,y}));await p.mouse.click(x,y);}catch(e){await p.screenshot({path:out+'/skip-failure.png'});console.log('FAILSTATE',plan.key,await p.evaluate(()=>({pending:S.pending_exam,phase:S.phase,html:document.querySelector('#ewPanelExam')?.innerText})));throw e;}await p.waitForFunction(()=>!S.pending_exam);await p.locator('.exam-demo').waitFor({state:'detached'});await p.waitForTimeout(100);
 const actionRows=await p.evaluate(()=>S.examination_activity.filter(x=>x.kind==='exam_action'));assert.equal(actionRows.at(-1).meta.status,'completed',plan.key);assert.equal(actionRows.at(-1).meta.duration_s,plan.duration_s);
 logs.push({key:plan.key,duration,result:await p.locator('#ewExamOutcome').innerText()});if(logs.length%10===0)console.log('Visible perform/skip/result',logs.length,'/',plans.length);
 }
 await p.locator('[data-ew-tab=talk]').click();assert.equal(await p.locator('#say').inputValue(),'Keep this unsent question while examining.');
 fs.writeFileSync(out+'/all-actions-results.json',JSON.stringify({logs,errors},null,2));assert.deepEqual(errors,[]);await c.close();
 // Filmstrips for individual review, using the same production renderer. Also
 // inspect changing geometry over a stage, not just an initial placeholder.
 const g=await b.newPage({viewport:{width:1600,height:1300}});await g.goto((process.env.CSE_TEST_URL||'http://127.0.0.1:8776/web/')+'exam-animation.css');await g.setContent('<style>body{margin:12px;background:#f5f7f2;color:#173f37;font:14px system-ui}.row{border-bottom:1px solid #b5c5bc;display:grid;grid-template-columns:260px repeat(3,1fr);gap:8px;align-items:center;height:190px}.exam-demo-canvas{height:154px;min-height:154px}.exam-demo-canvas svg{min-height:154px;height:154px}small{display:block;font-size:11px;line-height:1.25}h3{font-size:14px;margin:0 0 5px}</style>');await g.addStyleTag({path:root+'/web/exam-animation.css'});await g.addStyleTag({content:'.row{height:210px}.row .exam-demo-canvas,.row .exam-demo-canvas svg{height:160px;min-height:160px;max-height:160px}'});await g.addScriptTag({path:root+'/web/exam-animation.js'});
 const motion=await g.evaluate(plans=>plans.map(plan=>({key:plan.key,stages:plan.steps.map((s,i)=>{const t=plan.steps.slice(0,i).reduce((a,x)=>a+x.seconds,0),frames=[.05,.25,.5,.75,.95].map(u=>PCMExamAnimation.frame(plan,t+s.seconds*u,'back'));if(frames.some(f=>/NaN|Infinity|undefined/.test(f.svg)))throw Error(plan.key+' invalid geometry');return {caption:s.caption,action:s.action,motion:s.motion,variants:new Set(frames.map(f=>f.svg)).size,indices:frames.map(f=>f.index)};})})),plans);
 fs.writeFileSync(out+'/motion-samples.json',JSON.stringify(motion,null,2));
 for(let start=0;start<plans.length;start+=6){const batch=plans.slice(start,start+6);await g.evaluate(batch=>{document.body.innerHTML=batch.map(plan=>{let ts=[];if(plan.steps.length===1)ts=[.05,.5,.92].map(x=>x*plan.duration_s);else {const ii=[0,Math.floor(plan.steps.length/2),plan.steps.length-1];ts=ii.map(i=>plan.steps.slice(0,i).reduce((a,x)=>a+x.seconds,0)+plan.steps[i].seconds*.5);}
 return '<section class="row"><div><h3>'+plan.key+' · '+plan.duration_s+'s</h3><small>'+plan.position+'</small></div>'+ts.map(t=>{const f=PCMExamAnimation.frame(plan,t,'back');return '<div><div class="exam-demo-canvas">'+f.svg+'</div><small>'+t.toFixed(1)+'s · '+f.caption+'</small></div>';}).join('')+'</section>';}).join('');},batch);await g.screenshot({path:out+'/review-'+String(start/6+1).padStart(2,'0')+'.png',fullPage:true});}
 console.log('Catalog geometry sampled; 15 review sheets captured');
 }finally{await b.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
