/** Real WebGL rendering of every authored appearance plus load/retry transitions.
 * Uses isolated browser data; fixture messages contain only public visual state.
 * This is rendering coverage, not a test of the entire clinical workflow. */
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {execFileSync}=require('node:child_process');
const root=path.resolve(__dirname,'..'),out=process.env.CSE_TEST_OUTPUT||path.join(require('node:os').tmpdir(),'cse-patient-rendering');fs.mkdirSync(out,{recursive:true});
const base=process.env.CSE_TEST_URL||'http://127.0.0.1:8776/web/';
const states=JSON.parse(execFileSync('python3',['-c',`import json
from pcmcse import cases,presentation
out=[]
for base in cases.all_cases().values():
 for variant in ['base']+[v['id'] for v in base.get('variants',[])]:
  c=cases.resolve(base['id'],variant)
  out.append(dict(sessionId=c['id']+'-'+variant,caseId=c['id'],patientName=c['patient']['name'],phase='encounter',mode='coached',posture='seated',reducedMotion=True,appearance=presentation.appearance(c),eventSeq=1))
print(json.dumps(out))`],{cwd:root,encoding:'utf8'}));
assert.equal(states.length,82);assert.equal(new Set(states.map(s=>s.caseId)).size,34);
const results={sources:Object.fromEntries(['pcmcse/presentation.py','web/patient3d/index.html','web/patient3d/dist/room.js'].map(file=>[file,crypto.createHash('sha256').update(fs.readFileSync(path.join(root,file))).digest('hex')])),appearances:[],poses:[],recovery:[],errors:[]};
function inspect(){
 const x=window.pcmRoomInspection?.();if(!x)return null;
 const active=x.scene.getActiveMeshes().data.filter(m=>m&&m.getTotalVertices()>0&&m.isEnabled()&&m.isVisible&&m.name.startsWith('PCM_'));
 const roots=x.scene.transformNodes.filter(n=>n.name==='MPFB public patient'&&n.isEnabled());
 const face=x.anchors?.face;let projected=null;
 if(face){const V=face.constructor,M=x.camera.getWorldMatrix().constructor;projected=V.Project(face,M.Identity(),x.scene.getTransformMatrix(),x.camera.viewport.toGlobal(x.scene.getEngine().getRenderWidth(),x.scene.getEngine().getRenderHeight())).asArray();}
 return{roots:roots.length,meshes:active.map(m=>({name:m.name,vertices:m.getTotalVertices()})),face:face?.asArray(),projected,width:x.scene.getEngine().getRenderWidth(),height:x.scene.getEngine().getRenderHeight(),fps:x.fps,status:window.renderEvents?.filter(d=>d.type==='pcm-patient-status').at(-1),notice:document.querySelector('#trialStatus').textContent,noticeHidden:document.querySelector('#trialStatus').hidden};
}
async function send(p,s){await p.evaluate(s=>window.postMessage({type:'pcm-unity-state',state:s},location.origin),s);}
async function ready(p,s){await p.waitForFunction(s=>window.renderEvents?.some(d=>d.type==='pcm-patient-status'&&d.sessionId===s.sessionId&&d.status==='ready'),s,{timeout:70000});await p.waitForTimeout(200);}
function assertGeometry(data,label,faceVisible=true){assert.equal(data.roots,1,label+': one enabled patient');assert(data.meshes.some(m=>['PCM_PublicBody','PCM_AnatomicalBody'].includes(m.name)&&[8403,9247,14668,15460].includes(m.vertices)),label+': actual body in active render list '+JSON.stringify(data));assert(data.face?.every(Number.isFinite),label+': finite posed face');if(faceVisible){assert(data.projected[0]>=0&&data.projected[0]<=data.width&&data.projected[1]>=0&&data.projected[1]<=data.height,label+': face inside visible frame');}}
(async()=>{
 const b=await chromium.launch({channel:process.env.CSE_BROWSER||'chrome',headless:true});
 async function page(){const c=await b.newContext({viewport:{width:900,height:1000}});await c.addInitScript(()=>{window.renderEvents=[];window.addEventListener('message',e=>{if(e.origin===location.origin&&String(e.data?.type).startsWith('pcm-'))renderEvents.push(e.data);});});const p=await c.newPage();p.on('pageerror',e=>results.errors.push(e.message));return{p,c};}
 let {p,c}=await page();
 await p.goto(base+'patient3d/index.html');await p.waitForFunction(()=>window.pcmUnitySceneReady,{},{timeout:90000});
 for(const s of states){await send(p,s);await ready(p,s);const data=await p.evaluate(inspect);assertGeometry(data,s.sessionId);results.appearances.push({case:s.caseId,session:s.sessionId,appearance:s.appearance,...data});if(['msk-hand-stiffness-base','cardio-exertional-leg-pain-base','skin-contact-rash-base','heent-ear-pain-base'].includes(s.sessionId))await p.screenshot({path:path.join(out,s.caseId+'.png')});}
 results.loadMetrics=await p.evaluate(()=>renderEvents.filter(d=>d.type==='pcm-patient-metrics'));
 results.frameSample=await p.evaluate(()=>new Promise(resolve=>{const x=pcmRoomInspection(),start=performance.now();let frames=0;const observer=x.scene.onAfterRenderObservable.add(()=>frames++);setTimeout(()=>{x.scene.onAfterRenderObservable.remove(observer);resolve({elapsedMs:performance.now()-start,renderedFrames:frames,engineFps:x.fps,environment:'Desktop Chromium with software/device emulation; not physical iPad performance'});},2000);}));
 console.log('PASS all82 actual authored patient appearances visible across34 presentations');
 const assets=[states.find(s=>s.appearance.presentation==='male'),...['short-slender','standard','tall-full'].map(build=>states.find(s=>s.appearance.presentation==='female'&&s.appearance.bodyBuild===build))];
 for(const s of assets){await send(p,s);await ready(p,s);
  for(const [width,height] of [[768,1024],[1024,768]]){await p.setViewportSize({width,height});for(const posture of ['seated','supine','standing','prone']){const state={...s,sessionId:'pose-'+s.sessionId,posture};await send(p,state);await ready(p,state);await p.locator('[data-view=full]').click();await p.waitForTimeout(300);
   for(const anatomy of [false,true]){const button=p.locator('#coverageView');if((await button.getAttribute('aria-pressed'))===String(anatomy))await button.click();await p.waitForTimeout(250);const data=await p.evaluate(inspect);assertGeometry(data,`${s.appearance.presentation}-${s.appearance.bodyBuild}-${posture}-${anatomy}`,false);if(anatomy)assert(!data.meshes.some(m=>/^PCM_Public/.test(m.name)),'Covered meshes hidden');else if(s.appearance.presentation==='male')assert(!data.meshes.some(m=>m.name==='PCM_AnatomicalBody'),'Male anatomy does not project through trousers');const name=`${s.appearance.presentation}-${s.appearance.bodyBuild}-${posture}-${anatomy?'anatomy':'clothes'}-${width}`;results.poses.push({name,...data});if(!anatomy)await p.screenshot({path:path.join(out,name+'.png')});}
   await p.locator('#coverageView').click();
  }}
 }
 console.log('PASS four assets × four postures × two wardrobe states × both iPad orientations');
 await send(p,{...states[0],sessionId:'unassigned-legacy',appearance:{presentation:'female',age:45}});await p.waitForFunction(()=>!document.querySelector('#trialStatus').hidden);assert.match(await p.locator('#trialStatus').innerText(),/not assigned/);assert.equal(await p.locator('#trialStatus button').count(),0);results.recovery.push('Unassigned legacy state gives explicit limited notice and no nonfunctional retry');
 await send(p,{...states[0],sessionId:'return-to-assigned'});await ready(p,{sessionId:'return-to-assigned'});assertGeometry(await p.evaluate(inspect),'return to assigned');results.recovery.push('Returning to a reused valid asset reports ready for the new session');await c.close();
 ({p,c}=await page());let fail=true;await p.route('**/public-female-standard.glb*',r=>fail?r.abort('failed'):r.continue());await p.goto(base+'patient3d/index.html');await p.waitForFunction(()=>window.pcmUnitySceneReady,{},{timeout:90000});const standard=assets.find(s=>s.appearance.presentation==='female'&&s.appearance.bodyBuild==='standard');await send(p,standard);await p.getByRole('button',{name:'Retry patient',exact:true}).waitFor({timeout:60000});assert.match(await p.locator('#trialStatus').innerText(),/could not load|unavailable/);fail=false;await p.getByRole('button',{name:'Retry patient',exact:true}).click();await ready(p,standard);assertGeometry(await p.evaluate(inspect),'retry');results.recovery.push('Failed GLB load leaves actionable error; visible Retry patient recovers actual geometry');await c.close();
 ({p,c}=await page());let resolveRoute;const held=new Promise(r=>resolveRoute=r);let started;const began=new Promise(r=>started=r);await p.route('**/public-female-standard.glb*',async r=>{started();await held;await r.continue();});await p.goto(base+'patient3d/index.html');await p.waitForFunction(()=>window.pcmUnitySceneReady,{},{timeout:90000});await send(p,{...standard,sessionId:'abandoned-female'});await began;const male={...assets[0],sessionId:'replacement-male'};await send(p,male);await ready(p,male);resolveRoute();await p.waitForTimeout(5000);const latest=await p.evaluate(inspect);assertGeometry(latest,'late abandoned asset');assert.equal(latest.status.sessionId,male.sessionId);assert.equal(latest.status.status,'ready');assert.equal(await p.evaluate(()=>pcmRoomInspection().scene.transformNodes.filter(n=>n.name==='MPFB public patient').length),1);results.recovery.push('Late abandoned patient asset is disposed and cannot replace or cover the next patient');await c.close();
 ({p,c}=await page());let releaseLegacy,signalLegacy;const holdLegacy=new Promise(r=>releaseLegacy=r),startedLegacy=new Promise(r=>signalLegacy=r);await p.route('**/public-female-standard.glb*',async r=>{signalLegacy();await holdLegacy;await r.continue();});await p.goto(base+'patient3d/index.html');await p.waitForFunction(()=>window.pcmUnitySceneReady,{},{timeout:90000});await send(p,{...standard,sessionId:'loading-before-legacy'});await startedLegacy;await send(p,{...standard,sessionId:'legacy-during-load',appearance:{presentation:'female',age:45}});releaseLegacy();await p.waitForTimeout(5000);const legacy=await p.evaluate(inspect);assert.equal(legacy.status.status,'limited');assert.equal(legacy.roots,0);assert.match(legacy.notice,/not assigned/);await send(p,{...standard,sessionId:'ready-after-legacy'});await ready(p,{sessionId:'ready-after-legacy'});assertGeometry(await p.evaluate(inspect),'reused after legacy load');results.recovery.push('Late supported load cannot report ready for an unassigned legacy patient; returning to the valid appearance recovers');await c.close();
 fs.writeFileSync(path.join(out,'rendering.json'),JSON.stringify(results,null,2));assert.deepEqual(results.errors,[]);console.log('PASS failure, retry, unsupported legacy, reused session status and stale load disposal');await b.close();
})().catch(e=>{fs.writeFileSync(path.join(out,'rendering-failed.json'),JSON.stringify({...results,failure:e.stack},null,2));console.error(e);process.exit(1);});
