const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const fs=require('fs'),assert=require('assert/strict'),crypto=require('crypto');
const root=require('path').resolve(__dirname,'..'),out=process.env.CSE_TEST_OUTPUT||require('os').tmpdir()+'/cse-partner-print-layout',base=process.env.CSE_TEST_URL||'http://127.0.0.1:8775/web/';fs.mkdirSync(out,{recursive:true});
const sourceHashes=()=>Object.fromEntries(['web/engine.zip','web/partner-print.js','web/walkthrough-print.js','web/walkthrough-print.css','web/study.js','web/style.css'].map(f=>[f,crypto.createHash('sha256').update(fs.readFileSync(root+'/'+f)).digest('hex')]));
(async()=>{const initialSource=sourceHashes();const b=await chromium.launch({channel:'chrome',headless:true});const c=await b.newContext({viewport:{width:1440,height:900}}),page=await c.newPage();await page.goto(base+'#learn');await page.locator('#lessonGrid .lesson-card').first().waitFor({timeout:120000});
// Separate disposable runtime: fixtures establish data; visible chooser has its own workflow test.
const lessons=await page.evaluate(async()=>{const index=await(await fetch('/api/teaching')).json();const rows=[];for(const c of index.cases){for(const v of c.walkthroughs){const data=await(await fetch('/api/teaching/'+c.id+'?variant='+v.id)).json();if(data.error)throw Error(data.error);rows.push(data.lesson);}}return rows;});assert.equal(lessons.length,72);
fs.writeFileSync(out+'/lessons.json',JSON.stringify(lessons));
await page.route('**/print-test-harness.html',r=>r.fulfill({contentType:'text/html',body:'<!doctype html><html><head><title>Isolated print layout harness</title><link rel=stylesheet href=style.css></head><body></body></html>'}));await page.goto(base+'print-test-harness.html');await page.waitForFunction(()=>[...document.querySelectorAll('link')].every(x=>x.sheet));let results=[];
for(const l of lessons){for(const edition of ['patient','examiner','soap','study']){
 const state=await page.evaluate(async({l,edition})=>{const m=await import('/web/walkthrough-print.js');const {root,report}=await m.prepareWalkthrough(l,{edition});m.showWalkthroughPreview({onClose:()=>{},onPrint:()=>{}});const overflow=[];root.querySelectorAll('.pw-column').forEach(col=>{if(col.scrollHeight>col.clientHeight+1||col.scrollWidth>col.clientWidth+1)overflow.push(col.textContent.slice(0,150));});const qas=[...root.querySelectorAll('.rp-qa')];const atomic=qas.every(qa=>qa.getBoundingClientRect().bottom<=qa.closest('.pw-column').getBoundingClientRect().bottom+1);return{...report,overflow,atomic,text:root.innerText,diagnoses:[...root.querySelectorAll('.rp-note-assessment')].map(e=>e.textContent)};},{l,edition});
 assert.deepEqual(state.overflow,[],l.case_id+' '+edition+' overflow');assert(state.atomic,l.case_id+' split Q/A');assert(!state.text.includes('[object Object]')&&!state.text.includes('undefined'),l.case_id+' bad data');assert.equal(state.missingReferences.length,0);
 if(edition==='patient'){assert.equal(state.diagnoses.length,0);assert(!state.text.includes('Release finding:'));for(const s of l.partner_script.sections)assert(state.text.includes(s.title));}
 if(['soap','study'].includes(edition)){assert.equal(state.diagnoses.length,l.partner_note.assessment.length);assert(state.text.includes('complete demonstrated encounter'));}
 const filename=l.case_id+'--'+l.variant_id+'--'+edition;await page.pdf({path:out+'/'+filename+'.pdf',preferCSSPageSize:true,printBackground:true});
 if(l.variant_id==='base'&&['renal-flank-pain','cardio-febrile-cough','gi-epigastric-melena','cardio-orthopnea-edema','neuro-positional-vertigo','cardio-palpitations'].includes(l.case_id))await page.screenshot({path:out+'/'+filename+'.png'});
 const {text,...summary}=state;results.push(summary);await page.evaluate(async()=>{const m=await import('/web/walkthrough-print.js');m.clearWalkthroughPrint();});
 }console.log(l.case_id,l.variant_id,'PASS 4 editions');}
assert.deepEqual(sourceHashes(),initialSource,'Source changed during PDF validation');fs.writeFileSync(out+'/matrix.json',JSON.stringify({count:results.length,source:initialSource,results},null,2));await b.close();console.log('PASS',results.length,'PDFs');})().catch(e=>{console.error(e);process.exit(1)});
