/* Disposable tablet journeys. Start fixtures select a case; visible controls
   carry the interview, assistance, exam, note, and completion workflows. */
const pw=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const base=process.env.CSE_TEST_URL||'http://127.0.0.1:8776/web/';
const output=process.env.CSE_TEST_OUTPUT||'/private/tmp/cse-ipad-20260914/final';fs.mkdirSync(output,{recursive:true});
const kind=process.env.CSE_TEST_BROWSER||'chromium',repo=path.resolve(__dirname,'..');
const sizes=[[768,1024],[1024,768],[820,1180],[1180,820],[1440,900]],results=[];
let activePage;
(async()=>{const browser=await pw[kind].launch(kind==='chromium'?{channel:'chrome',headless:true}:{headless:true});
for(const [width,height] of sizes){
 const touch=width!==1440;const context=await browser.newContext({viewport:{width,height},hasTouch:touch,isMobile:touch,reducedMotion:'reduce'});
 const p=await context.newPage();activePage=p;const errors=[];p.on('pageerror',e=>errors.push(e.message));const tap=async locator=>touch?locator.tap():locator.click();
 const capture=async name=>{await p.screenshot({path:path.join(output,`${kind}-${width}-${name}.png`),fullPage:!touch});assert.equal(await p.evaluate(()=>matchMedia('(pointer:coarse)').matches),touch,'Capture must preserve emulated touch capability');};
 const noOverflow=async label=>{const value=await p.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth}));assert(value.scroll<=value.width+1,`${label} has horizontal overflow: ${JSON.stringify(value)}`);};
 await p.goto(base+'#practice');await p.locator('#btnStart').waitFor({timeout:120000});await p.evaluate(()=>begin(false,{case_id:'cardio-febrile-cough',variant_id:'base',learning_mode:'guided',mode:'type'}));await tap(p.locator('#skipEntrance'));await p.locator('#say').waitFor();const sid=await p.evaluate(()=>S.id);
 if(await p.locator('#ewVoice[aria-pressed=true]').count())await tap(p.locator('#ewVoice'));
 for(const text of ['What brings you in today?','When did your cough start?','Have you had fever or chills?','What medicines do you take?']){await p.locator('#say').fill(text);await tap(p.locator('#btnSay'));await p.waitForFunction(()=>!document.querySelector('#btnSay').disabled);}
 const draft='Have you noticed any other symptoms?\nPlease tell me about your breathing.';await p.locator('#say').fill(draft);
 const controls=await p.locator('#ewBedside,.ew-pos,#ewView,#toolChart,#ewVoice,#btnEnd,#btnSay,[data-ew-tab]').evaluateAll(es=>es.filter(e=>e.getClientRects().length&&!e.disabled).map(e=>({label:e.textContent.trim(),width:e.getBoundingClientRect().width,height:e.getBoundingClientRect().height})));
 if(touch){for(const r of controls)assert(r.height>=44,`${r.label} only ${r.height}px high`);assert.equal(await p.locator('#say').evaluate(e=>getComputedStyle(e).fontSize),'16px');}
 await noOverflow('Talk');await p.waitForFunction(()=>{const g=document.querySelector('#ewPanelGuide').getBoundingClientRect();return['guideDraft','guideNext'].every(id=>{const b=document.getElementById(id)?.getBoundingClientRect();return b&&b.height>=32&&b.top>=g.top-1&&b.bottom<=g.bottom+1});},{},{timeout:10000});await capture('talk');if(width===768){await tap(p.locator('#themeToggle'));assert.equal(await p.locator('html').getAttribute('data-theme'),'night');await p.waitForTimeout(500);await capture('talk-night');await tap(p.locator('#themeToggle'));await p.waitForTimeout(200);}
 await tap(p.locator('#ewBedside'));await tap(p.locator('.ew-bs[data-kind=suggestion]').filter({hasText:'How is this affecting your day'}));assert.equal(await p.locator('#say').inputValue(),draft);assert.equal(await p.locator('#ewSuggestionText').innerText(),'How is this affecting your day to day?');await tap(p.getByRole('button',{name:'Keep my draft',exact:true}));assert.equal(await p.locator('#say').inputValue(),draft);
 await tap(p.locator('#ewBedside'));assert(await p.getByRole('button',{name:'Return to selected draft',exact:true}).isVisible());await tap(p.locator('.ew-sheet-head button'));assert.equal(await p.evaluate(()=>document.activeElement.id),'ewBedside');await noOverflow('Bedside return');
 // The same draft survives orientation changes and reference/examination tabs.
 await p.setViewportSize({width:height,height:width});await p.waitForTimeout(100);assert.equal(await p.locator('#say').inputValue(),draft);await p.setViewportSize({width,height});
 await tap(p.locator('[data-ew-tab=exam]'));await p.locator('#manSearch').fill('general appearance');await tap(p.locator('[data-exam-action]').filter({hasText:'General appearance'}).first());await p.waitForFunction(()=>!!S.pending_exam);await p.waitForFunction(()=>!S.pending_exam&&S.transcript.some(t=>t.kind==='exam_finding'),{},{timeout:15000});assert.match(await p.locator('#ewExamOutcome').innerText(),/findings/i);await noOverflow('Exam result');await capture('exam-result');await tap(p.locator('#ewExamOutcome').getByRole('button',{name:/notes/i}));assert.match(await p.locator('#ewRecordLog').innerText(),/general|appears/i);await capture('notes');await tap(p.locator('[data-ew-tab=talk]'));assert.equal(await p.locator('#say').inputValue(),draft);
 await tap(p.locator('#toolChart'));await p.locator('.overlay-panel').waitFor();await noOverflow('Vitals');await capture('vitals');await p.setViewportSize({width:height,height:width});await noOverflow('Rotated vitals');await tap(p.locator('#overlayRoot').getByRole('button',{name:'Close',exact:true}));assert.equal(await p.evaluate(()=>document.activeElement.id),'toolChart');await p.setViewportSize({width,height});
 // Read a demonstration, leave it, then return to the same step. Teaching
 // does not claim an examination or replace the already obtained finding.
 if(width===820){const frame=p.frameLocator('#unityFrame');await tap(frame.locator('#techniqueLaunch'));p.once('dialog',d=>d.accept());await tap(frame.locator('[data-exam=cardiac]'));await tap(frame.locator('#techNext'));const heading=await frame.locator('#techniquePanel h2').innerText();await tap(frame.locator('.tech-close'));await tap(frame.locator('#techniqueLaunch'));assert.equal(await frame.locator('#techniquePanel h2').innerText(),heading);await tap(frame.locator('#techMenu'));await tap(frame.locator('#techResume'));assert.equal(await frame.locator('#techniquePanel h2').innerText(),heading);await capture('exam-guide');await tap(frame.locator('.tech-close'));assert.equal(await p.locator('#say').inputValue(),draft);}
 // Finish through the real transition. No fixture installs note data or results.
 await tap(p.locator('#btnEnd'));await tap(p.locator('.confirm-dialog button[value=confirm]'));await p.locator('#noteS').waitFor();const writing='Patient reports a cough beginning four days ago, with fever and chills. '+('History obtained in this disposable practice attempt. '.repeat(12));await p.locator('#noteS').fill(writing);await p.locator('#noteS').evaluate(e=>e.setSelectionRange(35,35));await p.locator('#noteO').fill('General appearance examined; other findings not obtained.');await p.locator('#noteS').focus();await p.locator('#noteS').evaluate(e=>e.setSelectionRange(35,35));
 if(width<1100){await tap(p.locator('button[data-note-view=reference]'));assert(await p.locator('#noteReference').isVisible());await tap(p.locator('[data-note-reference=chart]'));await noOverflow('Note reference');await capture('reference');await tap(p.locator('button[data-note-view=write]'));assert.equal(await p.locator('#noteS').inputValue(),writing);assert.equal(await p.locator('#noteS').evaluate(e=>e.selectionStart),35);}
 if(touch)assert.equal(await p.locator('#noteS').evaluate(e=>getComputedStyle(e).fontSize),'16px');await noOverflow('SOAP');await capture('soap');await p.waitForFunction(()=>noteSave.state==='saved');await p.reload();await p.locator('#noteS').waitFor({timeout:120000});assert.equal(await p.locator('#noteS').inputValue(),writing);assert.equal(await p.evaluate(()=>S.id),sid);
 await tap(p.locator('#btnSubmit'));await tap(p.locator('.confirm-dialog button[value=confirm]'));await p.waitForFunction(()=>S.phase==='submitted'&&RESULTS?.__for===S.id,{},{timeout:45000});await noOverflow('Feedback');await capture('feedback');assert.deepEqual(errors,[]);
 results.push({browser:kind,viewport:{width,height},touch,controls,passed:['populated interview','unsent draft preserved through Bedside and rotation','performed exam to Notes','rotated modal with restored focus','SOAP references with preserved writing and selection','saved note reload','submission feedback'],errors});console.log('PASS',kind,width,height);await context.close();
}
const assets={};for(const file of ['web/encounter-workspace.js','web/encounter-workspace.css','web/note-workspace.css','web/app.js','web/portal.js','web/portal.css','web/patient3d/index.html','web/patient3d/technique.css','web/patient3d/dist/room.js']){const bytes=fs.readFileSync(path.join(repo,file));assets[file]=crypto.createHash('sha256').update(bytes).digest('hex');}fs.writeFileSync(path.join(output,`${kind}-results.json`),JSON.stringify({results,assets},null,2));await browser.close();})().catch(async e=>{console.error(e);if(activePage){await activePage.screenshot({path:path.join(output,`${kind}-failure.png`),fullPage:true});console.log(await activePage.evaluate(()=>({url:location.href,phase:typeof S==='undefined'?null:S?.phase,dialogs:[...document.querySelectorAll('dialog[open]')].map(e=>e.textContent)})));}process.exit(1);});
