const fs=require('fs'),vm=require('vm'),assert=require('assert');const source=fs.readFileSync(require('path').join(__dirname,'../web/app.js'),'utf8');
const button={setAttribute(k,v){this[k]=v}},els={btnMic:button,interim:{}};let starts=0,stops=0,sent=0;
class SR{start(){starts++;this.onstart()}stop(){stops++;this.onend()}abort(){this.onend()}}
const c={window:{SpeechRecognition:SR,speechSynthesis:{speaking:false}},voice:{lastFinal:-1,muteUntil:0},S:{id:'mic-test',phase:'encounter'},$:s=>els[s.slice(1)],setPatientState(){},voiceBar(){},interruptPatient(){},notifyPublicState(){},esc:s=>s,alertNow(){},api(){},sendSay(){sent++;},stageUncertain(){},setTimeout,clearTimeout,Date};vm.createContext(c);vm.runInContext(source.slice(source.indexOf('function setupVoice(){'),source.indexOf('/* A turn the recognizer was unsure')),c);
const sleep=()=>new Promise(r=>setTimeout(r,450));
(async()=>{c.setupVoice();button.onclick();button.onclick();await sleep();assert.equal(starts,0,'fast on/off must not open microphone');button.onclick();await sleep();assert.equal(starts,1);assert(c.voice.listening);c.voice.rec.onend();await sleep();assert.equal(starts,2,'hands-free resumes after natural end');c.suppressListeningForPatient();await sleep();assert.equal(starts,2,'no listening during patient speech');button.onclick();c.resumeListeningAfterPatient();await sleep();await sleep();assert.equal(starts,2,'off stays off after speech');button.onclick();await sleep();c.voice.rec.onerror({error:'not-allowed'});c.voice.rec.onend();await sleep();assert(!c.voice.wanted);const count=starts;await sleep();assert.equal(starts,count,'permission error does not loop');c.startListening();await sleep();assert.equal(starts,count+1,'error-message retry works after hands-free was turned off');c.cancelListening();await sleep();assert.equal(starts,count+1,'Escape cancellation stays off');assert(!c.voice.wanted&&!c.voice.hands_free);c.voice.muteUntil=0;c.voice.rec.onresult({resultIndex:0,results:[Object.assign([{transcript:'late canceled words',confidence:0.9}],{isFinal:true})]});assert.equal(sent,0,'canceled recognition cannot submit late final results');console.log('PASS mic quick clicks, restart, speech suppression, off during speech, permission failure, error-button retry and cancellation');})().catch(e=>{console.error(e);process.exitCode=1});

// Patient presence must reflect microphone capture, not merely a focused draft.
const draft={value:'My unsent question'},presence={S:{phase:'encounter'},voice:{listening:false,patientSpeaking:false},window:{},document:{activeElement:draft},$:()=>draft};
vm.createContext(presence);vm.runInContext(source.slice(source.indexOf('function patientIsListening(){'),source.indexOf('function configurePatientSpeech(')),presence);
assert.equal(presence.patientIsListening(),false,'typing a draft must not imply microphone capture');
presence.voice.listening=true;assert.equal(presence.patientIsListening(),true,'active device capture is listening');
presence.voice.patientSpeaking=true;assert.equal(presence.patientIsListening(),false,'patient speech suppresses listening');
presence.voice.patientSpeaking=false;presence.voice.listening=false;presence.window.pcmAIRecording=true;assert.equal(presence.patientIsListening(),true,'active supported recording is listening');
presence.S.phase='note';assert.equal(presence.patientIsListening(),false,'note writing is never encounter listening');
console.log('PASS honest listening states while typing, recording, speaking and writing notes');
