/* Visible print workflows in a disposable browser, with isolated failure injection. */
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const assert=require('assert/strict'),fs=require('fs');
const base=process.env.CSE_TEST_URL||'http://127.0.0.1:8775/web/',out=process.env.CSE_TEST_OUTPUT||require('os').tmpdir()+'/cse-print-browser';fs.mkdirSync(out,{recursive:true});
(async()=>{const b=await chromium.launch({channel:'chrome',headless:true}),c=await b.newContext({viewport:{width:1440,height:900}}),p=await c.newPage(),errors=[];p.on('pageerror',e=>errors.push(e.message));
await p.goto(base+'#cases');await p.locator('#materialGrid .lesson-card').first().waitFor({timeout:120000});
await p.locator('#materialSearch').fill('cough');assert.equal(await p.locator('#materialGrid .lesson-card').count(),2);
await p.locator('#materialGrid .lesson-card').filter({hasText:'Fever, cough'}).click();await p.locator('#material-student').waitFor();
await p.screenshot({path:out+'/case-materials.png'});
// Track requests to prove safe handouts never request hidden lesson data.
await p.evaluate(()=>{const original=window.fetch;window.testSolutionCalls=[];window.fetch=(...args)=>{if(String(args[0]).includes('/api/teaching'))window.testSolutionCalls.push(String(args[0]));return original(...args);};});
async function open(edition){await p.locator('#material-'+edition).click();await p.waitForFunction(()=>document.body.hasAttribute('data-walkthrough-preview'));assert.equal(await p.evaluate(()=>pcmPrintReport.edition),edition);}
async function close(id){await p.locator('#pwClosePrint').click();assert.equal(await p.evaluate(()=>document.activeElement.id),id);assert.equal(await p.locator('body[data-walkthrough-preview]').count(),0);}
const original=await p.title();
await open('student');assert.equal(await p.evaluate(()=>pcmPrintReport.pages),3);assert.equal(await p.locator('.rp-topic,.rp-note-assessment,.rp-finding').count(),0);assert.equal(await p.locator('.rp-writing').count(),4);await close('material-student');
await open('blank');assert.equal(await p.evaluate(()=>pcmPrintReport.pages),2);assert.equal(await p.locator('.rp-writing').count(),4);await close('material-blank');
await open('doorway');assert.equal(await p.locator('.pw-page').count(),1);await close('material-doorway');assert.deepEqual(await p.evaluate(()=>testSolutionCalls),[]);
// A fixture creates a separate scored attempt. Actual controls must handle safe vs protected materials.
const sid=await p.evaluate(async()=>{const create=await(await fetch('/api/session',{method:'POST',body:JSON.stringify({case_id:'cardio-febrile-cough',learning_mode:'rehearsal'})})).json();await fetch('/api/session/'+create.id+'/start',{method:'POST',body:'{}'});return create.id;});
const getState=()=>p.evaluate(async id=>await(await fetch('/api/session/'+id)).json(),sid);const before=await getState();assert(!before.assisted);assert(before.phase_ends_at);
await open('student');await close('material-student');assert.equal((await getState()).phase_ends_at,before.phase_ends_at);assert(!(await getState()).assisted);
await p.locator('#material-patient').click();await p.locator('.confirm-dialog').waitFor();assert.match(await p.locator('.confirm-dialog').innerText(),/assisted practice/);await p.locator('.confirm-dialog button[value=cancel]').click();assert.equal(await p.locator('body[data-walkthrough-preview]').count(),0);assert(!(await getState()).assisted);
await p.locator('#material-patient').click();await p.locator('.confirm-dialog button[value=confirm]').click();await p.waitForFunction(()=>document.body.hasAttribute('data-walkthrough-preview'));assert((await getState()).assisted);assert.equal((await getState()).phase_ends_at,before.phase_ends_at);
assert.match(await p.title(),/Noah Rivera/);assert.equal(await p.locator('.rp-note-assessment').count(),0);
const hash=await p.evaluate(()=>location.hash);await p.locator('.rp-index [data-page-ref=allergies]').click();assert.equal(await p.evaluate(()=>location.hash),hash);assert.match(await p.locator('.rp-index [data-page-ref=allergies]').innerText(),/p\. \d+/);assert.match(await p.locator('#rp-allergies').innerText(),/Allergies/);
await p.screenshot({path:out+'/patient-preview.png'});await close('material-patient');assert.equal(await p.title(),original);
for(const edition of ['examiner','soap','study']){await open(edition);if(edition==='examiner'){assert.equal(await p.locator('.rp-note-assessment').count(),0);assert(await p.locator('.rp-exam-topic').count()>0);}else assert(await p.locator('.rp-note-assessment').count()>0);await p.pdf({path:out+'/'+edition+'-visible-workflow.pdf',preferCSSPageSize:true,printBackground:true});if(await p.locator('#pwClosePrint').isVisible())await close('material-'+edition);else assert.equal(await p.evaluate(()=>document.activeElement.id),'material-'+edition);}
await open('patient');await p.keyboard.press('Escape');assert.equal(await p.title(),original);assert.equal(await p.evaluate(()=>document.activeElement.id),'material-patient');
await p.setViewportSize({width:390,height:844});await p.screenshot({path:out+'/mobile-case-materials.png'});assert(await p.evaluate(()=>document.documentElement.scrollWidth<=innerWidth+1));
await open('blank');for(const id of ['#pwNativePrint','#pwClosePrint']){const r=await p.locator(id).boundingBox();assert(r.x>=0&&r.x+r.width<=390&&r.y>=0&&r.y+r.height<=844,JSON.stringify(r));}await p.screenshot({path:out+'/mobile-print-controls.png'});
await p.evaluate(()=>{window.print=()=>{window.testPrint={title:document.title,approved:document.body.dataset.walkthroughPrint};window.dispatchEvent(new Event('beforeprint'));window.dispatchEvent(new Event('afterprint'));};});await p.locator('#pwNativePrint').click();await p.waitForFunction(()=>!!window.testPrint);assert.equal(await p.evaluate(()=>testPrint.approved),'approved');assert.equal(await p.title(),original);
// Online lesson reflection and existing chooser remain available; returning must preserve the draft and position.
await p.setViewportSize({width:1440,height:900});await p.goto(base+'#learn/cardio-febrile-cough');await p.locator('#printLesson').waitFor();await p.waitForFunction(()=>!document.querySelector('#view').classList.contains('solution-locked'));
await p.locator('#recall-0').fill('Disposable reflection must survive printing.');await p.locator('#printLesson').scrollIntoViewIfNeeded();const place=await p.evaluate(()=>({x:scrollX,y:scrollY}));
await p.locator('#printLesson').click();await p.locator('#preparePrintDocument').click();await p.waitForFunction(()=>document.body.hasAttribute('data-walkthrough-preview'));await close('printLesson');assert.equal(await p.locator('#recall-0').inputValue(),'Disposable reflection must survive printing.');assert.deepEqual(await p.evaluate(()=>({x:scrollX,y:scrollY})),place);
// A failing style load must leave materials intact and retryable (the retired image storyboard is no longer a dependency).
const recoveryContext=await b.newContext({viewport:{width:1440,height:900}});const q=await recoveryContext.newPage();await q.goto(base+'#cases/renal-flank-pain');await q.locator('#material-student').waitFor({timeout:120000});await q.route('**/walkthrough-print.css*',r=>r.fulfill({status:503,body:'unavailable'}));await q.locator('#material-student').click();await q.locator('#printLessonStatus').filter({hasText:'could not be prepared'}).waitFor();assert.equal(await q.locator('body[data-walkthrough-preview]').count(),0);assert(await q.locator('#material-student').isEnabled());await q.unroute('**/walkthrough-print.css*');await q.locator('#material-student').click();await q.waitForFunction(()=>document.body.hasAttribute('data-walkthrough-preview'));await q.locator('#pwClosePrint').click();await recoveryContext.close();await p.bringToFront();
// Slow access checks may not cancel a user's open; a failed check may not leave answers printable.
await p.evaluate(()=>{const original=window.fetch;window.delayedAccessChecks=0;window.fetch=async(...args)=>{if(String(args[0]).endsWith('/api/teaching/status')){window.delayedAccessChecks++;await new Promise(r=>setTimeout(r,2300));}return original(...args);};});
await p.locator('#printLesson').click();await p.locator('#preparePrintDocument').click();await p.waitForFunction(()=>document.body.hasAttribute('data-walkthrough-preview'),{},{timeout:20000});assert(await p.evaluate(()=>delayedAccessChecks)>0);
await p.evaluate(()=>{const original=window.fetch;window.fetch=(url,...args)=>String(url).endsWith('/api/teaching/status')?Promise.reject(Error('Isolated access failure')):original(url,...args);});
await p.waitForFunction(()=>document.querySelector('#view').classList.contains('solution-locked')&&!document.body.hasAttribute('data-walkthrough-preview'),{},{timeout:10000});await p.emulateMedia({media:'print'});assert.equal(await p.locator('body[data-walkthrough-print=approved]').count(),0);assert.equal(await p.locator('#walkthroughPrint').isVisible(),false);assert.equal(await p.locator('.lesson-reader').isVisible(),false);
assert.deepEqual(errors,[]);fs.writeFileSync(out+'/interaction.json',JSON.stringify({result:'PASS',passed:['prominent navigation/search','seven direct material choices','safe payloads never request solutions','student printing preserves scored status/deadlines','protected answer cancel/explicit accept','cross-reference navigation','focus/title/scroll restoration','blank two-page workspace','390px reflow and print controls','Print button with simulated native lifecycle','saved legacy reflection retained','style failure and retry','slow access checks','failed access hides answers in print media'],errors},null,2));await b.close();console.log('PASS visible materials, protection, print lifecycle, narrow reflow and interruption recovery');})().catch(e=>{console.error(e);process.exit(1)});
