/** Real touch/WebKit renderer smoke test; does not claim physical iPad hardware certification. */
const {chromium,webkit}=require(process.env.PLAYWRIGHT_MODULE||'playwright');const assert=require('node:assert/strict'),fs=require('fs'),path=require('path'),crypto=require('crypto');
const {execFileSync}=require('child_process');const root=path.resolve(__dirname,'..'),out=process.env.CSE_TEST_OUTPUT||path.join(require('os').tmpdir(),'cse-patient-tablet');fs.mkdirSync(out,{recursive:true});
const base=process.env.CSE_TEST_URL||'http://127.0.0.1:8776/web/';
const fixture=JSON.parse(execFileSync('python3',['-c',"import json;from pcmcse import cases,presentation;c=cases.resolve('msk-hand-stiffness');print(json.dumps(dict(sessionId='tablet-render-test',caseId=c['id'],patientName=c['patient']['name'],phase='encounter',mode='coached',posture='seated',reducedMotion=True,appearance=presentation.appearance(c),eventSeq=1)))"],{cwd:root,encoding:'utf8'}));
const hashes=Object.fromEntries(['web/patient3d/dist/room.js','web/patient3d/index.html','web/patient3d/room.css','web/patient3d/technique.css'].map(p=>[p,crypto.createHash('sha256').update(fs.readFileSync(path.join(root,p))).digest('hex')]));
(async()=>{for(const [name,type] of [['chromium',chromium],['webkit',webkit]]){const browser=await type.launch(name==='chromium'?{channel:'chrome',headless:true}:{headless:true});const ctx=await browser.newContext({viewport:{width:390,height:650},hasTouch:true,isMobile:true,deviceScaleFactor:2});const page=await ctx.newPage(),errors=[];page.on('pageerror',e=>errors.push(e.message));await page.goto(base+'patient3d/index.html');await page.waitForFunction(()=>window.pcmUnitySceneReady,{},{timeout:120000});const state=fixture;await page.evaluate(s=>window.postMessage({type:'pcm-unity-state',state:s},location.origin),state);await page.waitForFunction(()=>window.pcmRoomInspection?.().scene.meshes.some(m=>m.name==='PCM_PublicBody'&&m.isEnabled()),{},{timeout:60000});await page.waitForTimeout(4000);
 const metrics=await page.evaluate(()=>({buttons:[...document.querySelectorAll('.view button,#coverageView,#techniqueLaunch')].filter(b=>b.getBoundingClientRect().height).map(b=>({name:b.getAttribute('aria-label')||b.textContent,width:b.getBoundingClientRect().width,height:b.getBoundingClientRect().height})),active:pcmRoomInspection().scene.getActiveMeshes().data.filter(m=>m&&m.isEnabled()&&m.name==='PCM_PublicBody').map(m=>m.getTotalVertices()),touch:getComputedStyle(document.querySelector('canvas')).touchAction}));assert(metrics.active.length);for(const b of metrics.buttons)assert(b.width>=44&&b.height>=44,JSON.stringify(b));assert.match(metrics.touch,/pan-y/);await page.screenshot({path:`${out}/${name}-touch-controls.png`});
 await page.locator('#techniqueLaunch').click();await page.locator('#techniquePanel').waitFor({state:'visible'});const guide=await page.evaluate(()=>({scroll:document.querySelector('#techniquePanel').scrollWidth,width:document.querySelector('#techniquePanel').clientWidth,close:document.querySelector('.tech-close').getBoundingClientRect().height}));assert(guide.scroll<=guide.width+1);assert(guide.close>=44);await page.screenshot({path:`${out}/${name}-guide.png`});await page.locator('.tech-close').click();
 if(name==='chromium'){const cdp=await ctx.newCDPSession(page);const before=await page.evaluate(()=>pcmRoomInspection().camera.alpha);await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:170,y:300}]});for(let x=180;x<=260;x+=20)await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x,y:300}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});const after=await page.evaluate(()=>pcmRoomInspection().camera.alpha);assert(Math.abs(after-before)>.1,'actual touch drag orbits');const vertical=after;await cdp.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x:170,y:300}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:171,y:400}]});await cdp.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert.equal(await page.evaluate(()=>pcmRoomInspection().camera.alpha),vertical,'vertical swipe does not orbit');}
 assert.deepEqual(errors,[]);fs.writeFileSync(`${out}/${name}-tablet.json`,JSON.stringify({hashes,metrics,guide,errors},null,2));console.log(name,metrics.active,guide);await browser.close();}})().catch(e=>{console.error(e);process.exit(1)});
