"""Approved abbreviations and the clinical concept lexicon.

APPROVED_ABBREVIATIONS is transcribed from the student manual's
"SOAP NOTE - Common Abbreviations" table (Table 1, 86 entries), plus the
forms used in the manual's own reference card and sample notes.  The manual
is the authority here; nothing was added for convenience.
"""

from __future__ import annotations

# --- Student manual, Table 1 -------------------------------------------------
APPROVED_ABBREVIATIONS = {
    "abd": "abdomen",
    "aids": "acquired immune deficiency syndrome",
    "etoh": "alcohol",
    "b": "black",
    "bun": "blood urea nitrogen",
    "bmi": "body mass index",
    "ccu": "cardiac care unit",
    "cpr": "cardiopulmonary resuscitation",
    "cva": "cerebrovascular accident",
    "cspine": "cervical spine",
    "cxr": "chest x-ray",
    "cc": "chief complaint",
    "copd": "chronic obstructive pulmonary disease",
    "cta": "clear to auscultation",
    "c/o": "complaining of",
    "cbc": "complete blood count",
    "ct": "computed tomography",
    "chf": "congestive heart failure",
    "cabg": "coronary artery bypass grafting",
    "dtr": "deep tendon reflexes",
    "dm": "diabetes mellitus",
    "ent": "ears, nose, and throat",
    "ecg": "electrocardiogram",
    "ekg": "electrocardiogram",
    "ed": "emergency department",
    "emt": "emergency medical technician",
    "e": "extended",
    "eom": "extraocular muscles",
    "ext": "extremities",
    "fh": "family history",
    "f": "female",
    "gi": "gastrointestinal",
    "gu": "genitourinary",
    "heent": "head, eyes, ears, nose and throat",
    "hvla": "high velocity, low amplitude",
    "hx": "history",
    "h/o": "history of",
    "hiv": "human immunodeficiency virus",
    "htn": "hypertension",
    "jvd": "jugular venous distention",
    "kub": "kidney, ureter, and bladder",
    "lmp": "last menstrual period",
    "l": "left",
    "lp": "lumbar puncture",
    "lspine": "lumbar spine",
    "mri": "magnetic resonance imaging",
    "m": "male",
    "meds": "medications",
    "mva": "motor vehicle accident",
    "mi": "myocardial infarction",
    "neuro": "neurologic",
    "nka": "no known allergies",
    "nkda": "no known drug allergies",
    "niddm": "non insulin-dependent diabetes mellitus",
    "nsr": "normal sinus rhythm",
    "po": "orally",
    "omt": "osteopathic manipulative treatment",
    "ppd": "packs per day",
    "ptt": "partial thromboplastin time",
    "pmh": "past medical history",
    "psh": "past surgical history",
    "pe": "physical examination",
    "pt": "prothrombin time",
    "perla": "pupils equal, react to light and accommodation",
    "rom": "range of motion",
    "rbc": "red blood cells",
    "rrr": "regular rate and rhythm",
    "ros": "review of systems",
    "r": "right",
    "rot": "rotated",
    "ro": "rule out",
    "sb": "side bent",
    "sh": "social history",
    "tspine": "thoracic spine",
    "tia": "transient ischemic attack",
    "us": "ultrasound",
    "uri": "upper respiratory tract infection",
    "u/a": "urinalysis",
    "w": "white",
    "wbc": "white blood cells",
    "wnl": "within normal limits",
    "yo": "year-old",
}

# Forms the manual itself uses in the reference card, checklists and sample
# notes but which are absent from Table 1.  Accepted, with a note, so the
# checker never contradicts the manual's own examples.
MANUAL_USAGE_ABBREVIATIONS = {
    "fdlmp": "first day of last menstrual period",
    "bp": "blood pressure",
    "hr": "heart rate",
    "rr": "respiratory rate",
    "t": "temperature",
    "p": "pulse",
    "o2": "oxygen",
    "all": "allergies",
    "gen": "general",
    "exts": "extremities",
    "b/l": "bilateral",
    "nsrrl": "neutral, sidebent right, rotated left",
    "otc": "over the counter",
    "pcp": "primary care physician",
    "bmp": "basic metabolic panel",
    "cmp": "comprehensive metabolic panel",
    "bnp": "b-type natriuretic peptide",
    "psa": "prostate specific antigen",
    "nsaid": "nonsteroidal anti-inflammatory drug",
    "nsaids": "nonsteroidal anti-inflammatory drugs",
    "s1": "first heart sound",
    "s2": "second heart sound",
    "s3": "third heart sound",
    "s4": "fourth heart sound",
    "cn": "cranial nerves",
}

ALL_APPROVED = dict(APPROVED_ABBREVIATIONS)
ALL_APPROVED.update(MANUAL_USAGE_ABBREVIATIONS)


# --- Review-of-systems system names -----------------------------------------
# From the manual's reference card: General / Skin / HEENT / Neck / Breasts /
# Respiratory / Cardiovascular / Gastrointestinal / Urinary / Genital /
# Musculoskeletal / Neurologic / Hematologic / Endocrine / Psychiatric
ROS_SYSTEMS = {
    "general": ["general", "constitutional", "fever", "chills", "weight loss",
                "weight gain", "fatigue", "malaise", "night sweats", "appetite"],
    "skin": ["skin", "integumentary", "rash", "itch", "itchy", "itching",
             "pruritus", "lesion", "hives", "dry skin", "bruise", "bruising"],
    "heent": ["heent", "head", "eyes", "ears", "nose", "throat", "headache",
              "vision", "hearing", "sore throat", "nasal", "rhinorrhea",
              "congestion", "tinnitus", "epistaxis", "vertigo"],
    "neck": ["neck", "stiff neck", "neck pain", "lymph", "thyroid"],
    "breasts": ["breast", "nipple"],
    "respiratory": ["respiratory", "pulmonary", "lungs", "cough", "shortness of breath",
                    "dyspnea", "wheez", "hemoptysis", "sputum", "chest tightness",
                    "sob"],
    "cardiovascular": ["cardiovascular", "cardiac", "heart", "chest pain",
                       "palpitation", "edema", "orthopnea", "claudication",
                       "syncope", "diaphoresis"],
    "gastrointestinal": ["gastrointestinal", "gi", "abdominal pain", "nausea",
                         "vomiting", "diarrhea", "constipation", "heartburn",
                         "melena", "hematochezia", "dysphagia", "bloating",
                         "stool", "reflux", "indigestion"],
    "urinary": ["urinary", "genitourinary", "gu", "dysuria", "hematuria", "frequency",
                "urgency", "nocturia", "incontinence", "urine", "urinat",
                "hesitancy", "stream"],
    "genital": ["genital", "sexual", "discharge", "menstrual", "vaginal", "penile",
                "erectile", "testicular"],
    "musculoskeletal": ["musculoskeletal", "msk", "joint", "muscle", "back pain",
                        "myalgia", "arthralgia", "stiffness", "swelling of joint",
                        "range of motion"],
    "neurologic": ["neurologic", "neuro", "numbness", "tingling", "weakness",
                   "seizure", "dizziness", "lightheaded", "confusion", "tremor",
                   "paresthesia", "memory"],
    "hematologic": ["hematologic", "bleeding", "bruising", "anemia", "clotting",
                    "lymphadenopathy"],
    "endocrine": ["endocrine", "polyuria", "polydipsia", "heat intolerance",
                  "cold intolerance", "hair loss", "thyroid symptom"],
    "psychiatric": ["psychiatric", "depress", "anxiety", "mood", "sleep",
                    "insomnia", "suicidal", "stress"],
}


# --- Concept lexicon ---------------------------------------------------------
# Maps a canonical concept id to the surface forms a student might write.
# Used by the documentation audit to decide *what* a note sentence asserts,
# independent of wording.  Case files add their own concepts on top of this.
CORE_CONCEPTS = {
    "tobacco_use": ["tobacco", "smoke", "smoker", "smoking", "smokes", "smoked",
                    "nonsmoker", "non-smoker", "cigarette", "vape", "nicotine",
                    "ppd", "pack year", "pack-year", "chewing tobacco"],
    "alcohol_use": ["alcohol", "etoh", "drink", "beer", "wine", "liquor"],
    "drug_use": ["illicit", "drug use", "drugs", "cocaine", "heroin", "marijuana",
                 "cannabis", "methamphetamine", "iv drug", "substance"],
    "allergies": ["allerg", "nkda", "nka", "no known drug"],
    "medications": ["medication", "meds", "taking", "prescription", "otc",
                    "over the counter"],
    "family_history": ["family history", "fh", "mother", "father", "sibling",
                       "brother", "sister", "parents"],
    "past_medical": ["past medical", "pmh", "medical condition", "medical problem",
                     "chronic"],
    "past_surgical": ["past surgical", "psh", "surgery", "surgeries", "operation",
                      "hospitaliz"],
    "fever": ["fever", "febrile", "temperature elevated", "chills"],
    "cough": ["cough"],
    "hemoptysis": ["hemoptysis", "coughing up blood", "blood in sputum",
                   "blood tinged sputum", "bloody sputum"],
    "dyspnea": ["shortness of breath", "sob", "dyspnea", "trouble breathing",
                "difficulty breathing", "short of breath", "winded"],
    "chest_pain": ["chest pain", "chest discomfort", "chest pressure",
                   "chest tightness"],
    "nausea": ["nausea", "nauseous", "queasy"],
    "vomiting": ["vomit", "emesis", "throwing up"],
    "diarrhea": ["diarrhea", "loose stool"],
    "constipation": ["constipation"],
    "headache": ["headache", "cephalgia", "head pain"],
    "dizziness": ["dizzy", "dizziness", "lightheaded", "vertigo"],
    "syncope": ["syncope", "fainting", "passed out", "loss of consciousness"],
    "weight_loss": ["weight loss", "lost weight", "losing weight"],
    "night_sweats": ["night sweat", "diaphoresis at night"],
    "rash": ["rash", "eruption", "skin lesion"],
    "dysuria": ["dysuria", "burning with urination", "pain with urination",
                "painful urination"],
    "hematuria": ["hematuria", "blood in urine", "blood in the urine"],
    "urinary_frequency": ["frequency", "urinating often", "frequent urination"],
    "nocturia": ["nocturia", "urinating at night", "up at night to urinate"],
    "edema": ["edema", "swelling of legs", "leg swelling", "ankle swelling"],
    "palpitations": ["palpitation", "heart racing", "fluttering"],
    "orthopnea": ["orthopnea", "worse lying flat", "worse when lying down",
                  "pillows to sleep"],
    "abdominal_pain": ["abdominal pain", "abd pain", "belly pain", "stomach pain",
                       "epigastric pain"],
    "back_pain": ["back pain", "low back pain", "lumbar pain"],
    "numbness": ["numbness", "numb"],
    "tingling": ["tingling", "paresthesia", "pins and needles"],
    "weakness": ["weakness", "weak"],
    "fatigue": ["fatigue", "tired", "malaise", "exhaust", "worn out", "no energy"],
    "sore_throat": ["sore throat", "throat pain", "pharyngitis", "odynophagia"],
    "rhinorrhea": ["runny nose", "rhinorrhea", "nasal discharge", "nasal drainage"],
    "congestion": ["congestion", "stuffy nose", "stuffed up", "sinus pressure"],
    "sick_contacts": ["sick contact", "anyone else sick", "similar symptoms",
                      "someone with the same"],
    "travel": ["travel", "traveled", "trip"],
    "easy_bruising": ["easy bruising", "bruises easily", "bruising"],
    "bleeding_gums": ["bleeding gums", "gum bleeding", "bleeding from the gums"],
    "joint_pain": ["joint pain", "arthralgia", "joint swelling"],
    "myalgia": ["myalgia", "muscle aches", "body aches"],
    "wheezing": ["wheezing", "wheeze"],
    "sputum": ["sputum", "phlegm", "productive cough"],
    "dysphagia": ["dysphagia", "trouble swallowing", "difficulty swallowing"],
    "heartburn": ["heartburn", "reflux", "indigestion", "acid reflux"],
    "blurred_vision": ["blurred vision", "blurry vision", "vision change",
                       "visual change", "diplopia", "double vision"],
    "hearing_loss": ["hearing loss", "tinnitus", "ringing in the ears"],
    "polyuria": ["polyuria", "urinating large amounts"],
    "polydipsia": ["polydipsia", "excessive thirst"],
    "insomnia": ["insomnia", "trouble sleeping", "poor sleep"],
    "anxiety": ["anxiety", "anxious"],
    "depression": ["depression", "depressed", "low mood"],
    "sick_contact": ["sick contacts", "anyone else sick"],
    "chills": ["chills", "rigors"],
    "jaundice": ["jaundice", "yellowing", "icterus", "anicteric", "icteric"],
    "lymphadenopathy": ["lymphadenopathy", "swollen glands", "swollen nodes"],
}

# Physical-exam findings the note can assert, keyed by the exam maneuver that
# must have been performed for the assertion to be supported.
EXAM_CLAIM_CONCEPTS = {
    "lungs_auscultation": ["lungs", "lung", "cta", "clear to auscultation",
                           "breath sounds", "rales", "crackles", "rhonchi",
                           "wheez", "auscultat.*lung", "air movement"],
    "lungs_percussion": ["percussion", "percuss", "dullness", "dull to percussion",
                         "resonan", "hyperresonan"],
    "lungs_fremitus": ["fremitus", "tactile fremitus"],
    "heart_auscultation": ["heart", "rrr", "regular rate and rhythm", "murmur",
                           "s1", "s2", "s3", "s4", "gallop", "rub", "tachycardic",
                           "bradycardic"],
    "abdomen_auscultation": ["bowel sound", "bowel sounds", "borborygmi", "bruit"],
    "abdomen_palpation": ["soft", "nontender", "non-tender", "tender", "guarding",
                          "rebound", "mass", "organomegal", "hepatomegal",
                          "splenomegal", "distended", "nondistended"],
    "abdomen_percussion": ["percuss", "tympan", "shifting dullness", "dullness"],
    "skin_inspection": ["skin", "rash", "lesion", "macule", "papule", "vesicle",
                        "erythema", "no rash"],
    "heent_oropharynx": ["throat", "oropharynx", "pharyn", "tonsil", "exudate",
                         "erythema of throat", "uvula", "oral mucosa"],
    "heent_ears": ["ear", "tympanic membrane", "tm ", "canal", "otoscop"],
    "heent_nose": ["nose", "nares", "turbinate", "nasal mucosa", "septum"],
    "heent_eyes": ["eyes", "perla", "pupils", "conjunctiv", "sclera", "eom",
                   "fundoscop"],
    "heent_sinuses": ["sinus", "sinus tenderness", "frontal", "maxillary"],
    "lymph_nodes": ["lymph", "node", "adenopathy", "lymphadenopathy", "cervical node"],
    "thyroid": ["thyroid", "goiter"],
    "neuro_cranial_nerves": ["cranial nerve", "cn i", "cn ii", "cn 2", "cn ii-xii",
                             "cn i-xii", "cnii-xii"],
    "neuro_motor": ["motor", "strength", "5/5", "muscle strength"],
    "neuro_sensory": ["sensory", "sensation", "light touch", "pinprick"],
    "neuro_reflexes": ["reflex", "dtr", "2+ reflex", "babinski"],
    "neuro_gait": ["gait", "walking", "romberg", "ambulat"],
    "msk_rom": ["range of motion", "rom", "flexion", "extension", "rotation",
                "side bending"],
    "msk_palpation": ["paraspinal", "spasm", "point tender", "tenderness to palpation",
                      "tender to palpation"],
    "special_slr": ["straight leg", "slr", "lasegue"],
    "extremities": ["extremities", "exts", "pulses", "capillary refill", "clubbing",
                    "cyanosis"],
    "osteopathic": ["osteopathic", "somatic dysfunction", "tspine", "cspine",
                    "lspine", "t1", "t2", "t3", "t4", "t5", "t6", "t7", "t8", "t9",
                    "t10", "t11", "t12", "l1", "l2", "l3", "l4", "l5",
                    "sidebent", "side bent", "rotated", "flexed", "extended",
                    "tart", "tissue texture"],
    "general_appearance": ["general", "gen:", "well appearing", "no acute distress",
                           "nad", "alert", "oriented", "distress", "ill appearing",
                           "well developed", "well nourished"],
    "vitals": ["vitals", "bp", "blood pressure", "hr", "heart rate", "pulse",
               "temp", "temperature", "rr", "respiratory rate", "pulse ox",
               "spo2", "o2 sat", "weight", "height", "bmi"],
}

# Words that are legitimate clinical vocabulary even though they contain
# "normal".  The rubric's "No credit for 'Normal'" targets vague summary
# statements such as "abdominal exam normal", not these.
NORMAL_SAFE_TERMS = [
    "normal sinus rhythm", "nsr", "normocephalic", "normoactive",
    "normotensive", "normal saline", "abnormal", "normoglycemic",
    "normocytic", "normochromic", "normal flexion",
]

# Vague summary phrases the Objective rubric rejects.
VAGUE_OBJECTIVE_PATTERNS = [
    r"\b(exam|examination)\s+(is\s+|was\s+)?normal\b",
    r"\bnormal\s+(exam|examination)\b",
    r"^\s*normal\s*$",
    r"\b(unremarkable|benign|nonfocal|non-focal)\s*$",
    r"\bwithin normal limits\b",
    r"\bwnl\b",
    r"\ball\s+(other\s+)?(systems|exams?)\s+normal\b",
    r"\bno abnormalities\b",
    r"\bnothing (remarkable|notable)\b",
]


# Symptom concepts a standardized patient can plausibly deny on the spot when a
# case script does not cover them.  A denial only ever enters the record because
# the student ASKED -- silence still never becomes a negative.  Identity,
# history and social concepts are deliberately absent: those need a real
# scripted answer, never an improvised "no".
DENIABLE_SYMPTOMS = [
    "fever", "cough", "hemoptysis", "dyspnea", "chest_pain", "nausea", "vomiting",
    "diarrhea", "constipation", "headache", "dizziness", "syncope", "weight_loss",
    "night_sweats", "rash", "dysuria", "hematuria", "urinary_frequency",
    "nocturia", "edema", "palpitations", "orthopnea", "abdominal_pain",
    "back_pain", "numbness", "tingling", "weakness", "fatigue", "sore_throat",
    "rhinorrhea", "congestion", "sick_contacts", "travel",
]
